Feature/checkbirthdate
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #100
Opened 2024-02-23 00:19 UTC by Cardamced

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [X] Frontend
- [X] Backend
- [ ] Other: .....

## General checklist:

- [X] My code follows the style guidelines of this project
- [X] I ran `bun run format`/`bun run lint` before commit
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation where needed
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] I have updated `develop` and merged to my branch before submitting pull request
- [X] My pull request generate no conflicts with `develop` branch
- [X] I requested code review from other team members

## Frontend checklist:

- [X] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [X] My `Javascript` generate no new console errors
- [X] I tested my code cross browsers
- [X] My slice is pixel perfect for both desktop and mobile according to design
- [X] I conducted basic QA to assure all features are working
- [X] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [X] I added description to admin fields in hard-to-understand areas
- [X] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-23 08:29 UTC, No3ml3 approved these changes, later dismissed

2024-02-23 08:49 UTC, jaalazard submitted a review, later dismissed

2024-02-26 08:13 UTC, YDrogen requested changes

2024-02-26 08:13 UTC, YDrogen commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
nope

2024-02-26 08:36 UTC, Cardamced commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
Done.

2024-02-26 08:56 UTC, YDrogen commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
Non

2024-02-26 09:22 UTC, Cardamced commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
J'aurions cru. Dingue. Maintenant c'est bon.

2024-02-26 09:36 UTC, YDrogen commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
Toujours pas :(

2024-02-26 09:41 UTC, Cardamced commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
Running gag. :'-/

2024-02-26 10:51 UTC, YDrogen approved these changes

2024-02-26 10:51 UTC, merged