Feature/transition page
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #104
Opened 2024-02-23 13:27 UTC by Justicesvr

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-23 13:34 UTC, jaalazard submitted a review, later dismissed

2024-02-23 14:52 UTC, No3ml3 approved these changes, later dismissed

2024-02-23 14:56 UTC, No3ml3 submitted a review, later dismissed

2024-02-23 14:59 UTC, jaalazard approved these changes, later dismissed

2024-02-23 15:00 UTC, Cardamced approved these changes, later dismissed

2024-02-27 10:06 UTC, jaalazard submitted a review, later dismissed

2024-02-27 10:06 UTC, No3ml3 approved these changes, later dismissed

2024-02-27 13:34 UTC, YDrogen requested changes

2024-02-27 13:34 UTC, YDrogen commented on packages/frontend/web/src/pages/Login.tsx
> +      {!!isLoading && (
Pourquoi `!!` ?

2024-02-27 13:34 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      {!!isShake && (
?

2024-02-27 13:34 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/SoftDrinks.tsx
> +        <div className="peer h-6 w-11 rounded-full bg-gray-700  after:absolute after:start-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-700  after:bg-wh
double espaces x2

2024-02-27 13:34 UTC, YDrogen commented on packages/frontend/web/src/pages/Community.tsx
> +              className='absolute top-2 z-20  h-[11rem] w-[11rem]'
idem

2024-02-27 13:52 UTC, Justicesvr commented on packages/frontend/web/src/pages/Login.tsx
> +      {!!isLoading && (
je ne sais pas

2024-02-27 13:52 UTC, Justicesvr commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      {!!isShake && (
mais ca marche

2024-02-27 14:00 UTC, No3ml3 submitted a review, later dismissed

2024-02-27 14:42 UTC, Cardamced approved these changes, later dismissed

2024-02-27 15:13 UTC, YDrogen commented on packages/frontend/web/src/pages/Login.tsx
> +      {!!isLoading && (
Ça load ou ça load pas du coup ? T'as inversé ta condition là, c'est normal ?

2024-02-27 15:13 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      {!!isShake && (
idem

2024-02-27 15:25 UTC, No3ml3 approved these changes

2024-02-27 15:27 UTC, jaalazard approved these changes

2024-02-27 15:35 UTC, YDrogen approved these changes

2024-02-27 15:35 UTC, merged