Release/v0.2.0
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #108
Opened 2024-02-27 09:16 UTC by No3ml3

## Description

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-27 09:18 UTC, jaalazard approved these changes, later dismissed

2024-02-27 10:05 UTC, Justicesvr approved these changes, later dismissed

2024-02-27 15:39 UTC, YDrogen requested changes

2024-02-27 15:39 UTC, YDrogen commented on packages/frontend/web/src/components/CardImage.tsx
> +    return `${import.meta.env.VITE_BACKEND_URL}/${image}`;
Mauvaise URL

2024-02-28 09:01 UTC, No3ml3 commented on packages/frontend/web/src/components/CardImage.tsx
> +    return `${import.meta.env.VITE_BACKEND_URL}/${image}`;
comprends pas c quoi mauvaise url

2024-02-28 09:03 UTC, YDrogen commented on packages/frontend/web/src/components/CardImage.tsx
> +    return `${import.meta.env.VITE_BACKEND_URL}/${image}`;
Le lien n'est pas bon, ça ne fonctionnera pas tel quel

2024-02-28 09:11 UTC, No3ml3 commented on packages/frontend/web/src/components/CardImage.tsx
> +    return `${import.meta.env.VITE_BACKEND_URL}/${image}`;
ca focntionne sur localhost ou alors il faut que je rajoute /uploads car le ${import.meta.env.VITE_BACKEND_URL} ne comprends pas uploads ????

2024-02-28 09:27 UTC, YDrogen commented on packages/frontend/web/src/components/CardImage.tsx
> +    return `${import.meta.env.VITE_BACKEND_URL}/${image}`;
Comme on a fait avec le déploiement pour remplacer la variable d'env par `/api`, il faut faire pareil avec `/uploads`

2024-02-28 09:40 UTC, Justicesvr submitted a review, later dismissed

2024-02-28 10:01 UTC, jaalazard approved these changes

2024-02-28 10:08 UTC, Justicesvr approved these changes

2024-02-28 10:09 UTC, YDrogen approved these changes

2024-02-28 10:15 UTC, Cardamced approved these changes

2024-02-28 10:17 UTC, merged