Feature/database data
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #11
Opened 2023-11-30 19:03 UTC by jaalazard

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [x ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ x] Backend
- [ ] Other: .....

## General checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I ran `bun run format`/`bun run lint` before commit
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation where needed
- [x ] My changes generate no new warnings
- [x ] I have checked my code and corrected any misspellings
- [x ] I have updated `develop` and merged to my branch before submitting pull request
- [x ] My pull request generate no conflicts with `develop` branch
- [x ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-30 22:31 UTC, Cardamced commented on packages/backend/forge/README.md
Vraiment besoin de push le readme du dossier forge ? C'est juste une question... ;-)

2023-11-30 22:32 UTC, Cardamced submitted a review, later dismissed
Moyennant le commentaire que j'ai laissé, c'est bon pour moi.

2023-12-01 08:07 UTC, No3ml3 approved these changes, later dismissed

2023-12-01 10:18 UTC, No3ml3 approved these changes, later dismissed

2023-12-01 10:19 UTC, Cardamced approved these changes, later dismissed
Ok pour moi.

2023-12-01 10:50 UTC, No3ml3 approved these changes, later dismissed

2023-12-01 11:10 UTC, Cardamced submitted a review, later dismissed
Cool.

2023-12-01 11:13 UTC, YDrogen requested changes

2023-12-01 11:13 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +        capacity SMALLINT UNSIGNED NOT NULL,
Non, la migration a déjà été merge, il faut en faire une nouvelle

2023-12-01 11:20 UTC, No3ml3 submitted a review, later dismissed

2023-12-01 11:22 UTC, Cardamced submitted a review, later dismissed
Bien.

2023-12-01 13:01 UTC, YDrogen requested changes

2023-12-01 13:01 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231201111652-new-database-structure.ts
Toutes ces tables existent déjà, non ? Pourquoi les recréer ?

2023-12-01 13:18 UTC, No3ml3 submitted a review, later dismissed

2023-12-01 13:22 UTC, Cardamced submitted a review, later dismissed
Parfait.

2023-12-01 13:45 UTC, YDrogen requested changes

2023-12-01 13:45 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231201111652-edit-glass-table.ts
Maintenant, il manque le `down`
Chaque migration doit avoir un `up` et un `down`

2023-12-01 13:52 UTC, No3ml3 submitted a review, later dismissed

2023-12-01 13:57 UTC, Cardamced approved these changes, later dismissed
Ok pour moi.

2023-12-01 14:15 UTC, YDrogen requested changes

2023-12-01 14:15 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231201111652-edit-glass-table.ts
> +      MODIFY capacity TINYINT UNSIGNED NOT NULL;;
```suggestion
      MODIFY capacity TINYINT UNSIGNED NOT NULL;
```
:(

2023-12-01 14:18 UTC, No3ml3 approved these changes

2023-12-01 14:20 UTC, Cardamced approved these changes

2023-12-01 14:28 UTC, YDrogen approved these changes

2023-12-01 14:28 UTC, merged