Feature/auth backend
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #12
Opened 2023-12-04 15:37 UTC by Cardamced

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-04 16:03 UTC, No3ml3 approved these changes, later dismissed

2023-12-04 16:12 UTC, jaalazard approved these changes

2023-12-04 18:15 UTC, Justicesvr approved these changes, later dismissed

2023-12-04 18:15 UTC, Justicesvr commented on packages/backend/api/src/middlewares/validate-register.ts
cela m'a l'air pas mal, avec les validations :)

2023-12-04 18:17 UTC, jaalazard approved these changes, later dismissed
Encore mieux qu'en vidéo !

2023-12-05 09:07 UTC, YDrogen requested changes

2023-12-05 09:07 UTC, YDrogen commented on package.json
> +    "jose": "^5.1.3"
Les dépendances ne vont pas ici

2023-12-05 10:46 UTC, Cardamced commented on package.json
> +    "jose": "^5.1.3"
Résolu, les dépendances sont ôtées du package.json de la racine et seulement présentes dans le package.json du backend.

2023-12-05 10:48 UTC, Justicesvr submitted a review, later dismissed

2023-12-05 10:49 UTC, No3ml3 submitted a review, later dismissed

2023-12-05 11:26 UTC, YDrogen requested changes

2023-12-05 11:26 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +        email VARCHAR(254) NOT NULL,
Une fois qu'une migration a été acceptée, on n'y touche plus : Il faut en faire une autre pour modifier la bdd

2023-12-05 11:26 UTC, YDrogen commented on packages/types/src/auth.ts
> +  created_at: Date;
Pourquoi le `created_at` aurait besoin d'être dans le body ?

2023-12-05 11:26 UTC, YDrogen commented on packages/types/src/auth.ts
Il s'agit du Login ou du Register ? Si ce n'est pas les deux, il faut 2 types différents

2023-12-05 11:26 UTC, YDrogen commented on packages/backend/api/src/middlewares/validate-login.ts
> +  body('pseudo').exists().isLength({ max: 60 }),
Il faut l'email ET le pseudo pour se connecter ??

2023-12-05 11:26 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +});
Très belle faille de sécurité ici
Bien joué au reste de l'équipe qui approuve 👍

2023-12-05 11:57 UTC, Cardamced commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +        email VARCHAR(254) NOT NULL,
Ok, je laisse 255. On changera ça plus tard.

2023-12-05 14:58 UTC, Cardamced commented on packages/types/src/auth.ts
> +  created_at: Date;
Aucune idée précise... j'ai simplement ajouté les champs qui correspondaient au user. Mais je l'enlève.

2023-12-05 16:01 UTC, Cardamced commented on packages/backend/api/src/auth.ts
> +});
En effet... ça saute !

2023-12-05 19:41 UTC, Cardamced commented on packages/types/src/auth.ts
Ok. C'est bien les deux. J'ai créé deux fichiers distincts : auth-login.ts et auth-register.ts.

2023-12-05 19:42 UTC, Cardamced commented on packages/backend/api/src/middlewares/validate-login.ts
> +  body('pseudo').exists().isLength({ max: 60 }),
L'email suffit, après réflexion.

2023-12-06 08:23 UTC, No3ml3 submitted a review, later dismissed

2023-12-06 09:14 UTC, jaalazard submitted a review, later dismissed

2023-12-06 09:15 UTC, Cardamced commented on packages/backend/api/src/middlewares/validate-register.ts
Il vous en prie. :-)

2023-12-06 09:17 UTC, Justicesvr approved these changes, later dismissed

2023-12-06 09:19 UTC, YDrogen requested changes

2023-12-06 09:19 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231205142035-edit-user.ts
> +    await trx.schema.dropTable('item').ifExists().execute();
Hop la ligne en trop

2023-12-06 09:19 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +        email VARCHAR(254) NOT NULL,
Il faut retirer cette modif du coup

2023-12-06 09:34 UTC, Cardamced commented on packages/backend/migrations/src/migrations/20231205142035-edit-user.ts
> +    await trx.schema.dropTable('item').ifExists().execute();
C'est corrigé.

2023-12-06 09:41 UTC, Justicesvr approved these changes, later dismissed

2023-12-06 09:44 UTC, No3ml3 approved these changes, later dismissed

2023-12-06 09:45 UTC, YDrogen requested changes
Il suffit pas de resolve les conversations, il faut aussi faire les changements demandés !!!

2023-12-06 09:52 UTC, Cardamced commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +        email VARCHAR(254) NOT NULL,
C'est fait. Je n'avais pas la deuxième partie du message.

2023-12-06 09:53 UTC, No3ml3 approved these changes

2023-12-06 09:54 UTC, Justicesvr approved these changes

2023-12-06 09:55 UTC, No3ml3 approved these changes

2023-12-06 10:10 UTC, YDrogen approved these changes

2023-12-06 10:10 UTC, merged