feat: generation of an alcohols list based on the strength selected b…
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #13
Opened 2023-12-05 18:25 UTC by jaalazard

…y the user

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [x ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ x] Backend
- [ ] Other: .....

## General checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I ran `bun run format`/`bun run lint` before commit
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation where needed
- [ x] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings
- [x ] I have updated `develop` and merged to my branch before submitting pull request
- [ x] My pull request generate no conflicts with `develop` branch
- [ x] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ x] I tested admin by manually adding content from zero
- [ x] I created easy to use admin experience which is self-explanatory
- [ x] I added description to admin fields in hard-to-understand areas
- [x ] I followed guidelines for naming `Typescript` variables
- [ x] I conducted basic QA to assure all features are working

2023-12-05 18:38 UTC, Cardamced commented
T'as un souci dans le frontend, apparemment.

2023-12-05 18:57 UTC, No3ml3 approved these changes, later dismissed

2023-12-05 18:58 UTC, No3ml3 commented
il (te) manque des cases

2023-12-05 19:29 UTC, Cardamced approved these changes, later dismissed

2023-12-06 08:48 UTC, No3ml3 submitted a review, later dismissed

2023-12-06 08:54 UTC, Cardamced submitted a review, later dismissed

2023-12-06 09:26 UTC, YDrogen requested changes

2023-12-06 09:26 UTC, YDrogen commented on packages/backend/api/src/router.ts
> +  const degree = Number.parseInt(req.params.level);
Pourquoi `Number.` ?

2023-12-06 09:26 UTC, YDrogen commented on packages/backend/api/src/services/alcohol-service.ts
> +import type { Ingredient } from '@app/types';
Une seule ligne possible

2023-12-06 09:26 UTC, YDrogen commented on packages/backend/api/src/services/alcohol-service.ts
Une raison pour ne pas utiliser le query builder [(doc)](https://kysely.dev/docs/examples/WHERE/conditional-where-calls) ?

2023-12-06 09:26 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +        `http://localhost:3333/api/alcohols/${selectedLevel}`,
Une pensée pour les copains qui sont pas sur `localhost` 🙏 
L'URL du backend se trouve dans les variables d'environnement, il y a un exemple sur la page Home

2023-12-06 09:28 UTC, jaalazard commented on packages/backend/api/src/router.ts
> +  const degree = Number.parseInt(req.params.level);
C'est ESLint qui m'a forcé moi je ne voulais pas

2023-12-06 09:29 UTC, jaalazard commented on packages/backend/api/src/services/alcohol-service.ts
C'était une option non ?

2023-12-06 10:10 UTC, Cardamced submitted a review, later dismissed
Ok pour moi.

2023-12-06 10:10 UTC, No3ml3 approved these changes, later dismissed

2023-12-06 10:14 UTC, Justicesvr submitted a review, later dismissed

2023-12-06 11:19 UTC, YDrogen approved these changes

2023-12-06 11:19 UTC, YDrogen requested changes
conflit

2023-12-06 11:22 UTC, No3ml3 approved these changes

2023-12-06 11:22 UTC, Cardamced approved these changes

2023-12-06 12:27 UTC, YDrogen approved these changes

2023-12-06 12:28 UTC, merged