Feature/cocktail detail upload
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #15
Opened 2023-12-06 16:15 UTC by Justicesvr

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-07 08:11 UTC, No3ml3 approved these changes, later dismissed

2023-12-07 08:38 UTC, jaalazard approved these changes, later dismissed
Ça fonctionne, rien à ajouter

2023-12-07 09:04 UTC, YDrogen requested changes

2023-12-07 09:04 UTC, YDrogen commented on .env.sample
Il faut laisser le saut de ligne vide en fin de fichier

2023-12-07 09:04 UTC, YDrogen commented on packages/backend/api/package.json
Les packages `@types` vont dans les `devDeps`

2023-12-07 09:04 UTC, YDrogen commented on packages/types/src/database.ts
> +export type Cocktail = Selectable<CocktailTable> | undefined;
Surtout pas, ça peut casser le typage de la BDD ça

2023-12-07 09:04 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +            src='/packagescocktail-placeholder.png'
Y'a pas un problème ici ? 🤔

2023-12-07 09:04 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +/* eslint-disable @typescript-eslint/restrict-template-expressions */
Hop hop hop, qu'est-ce que c'est que ça ? 🤔

2023-12-07 09:04 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231205145821-add-anecdote-field.ts
> +    `.execute(trx);
Ne fonctionne pas

2023-12-07 09:04 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +      signal: signal,
Tu peux
```suggestion
      signal,
```

2023-12-07 09:04 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +      throw new Error(error);
Il faut éviter les `throw` en React quand ce n'est pas catch, ça fait / peut faire crash l'application

2023-12-07 09:04 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
Il faudrait un return conditionnel, quand le cocktail n'existe pas / n'est pas trouvé
Ça évite de mettre `cocktail?.` partout, c'est pas ouf d'afficher une page vide quand le cocktail n'existe pas, autant afficher un message d'erreur, page 404, ou rediriger

2023-12-07 09:04 UTC, YDrogen commented on packages/types/src/cocktail-detail.ts
> +export type Inputs = {
Inputs de quoi ? Nom de type pas assez précis

2023-12-07 11:15 UTC, No3ml3 approved these changes, later dismissed

2023-12-07 13:45 UTC, jaalazard approved these changes, later dismissed

2023-12-07 13:47 UTC, Cardamced approved these changes, later dismissed
Peccab'.

2023-12-07 15:06 UTC, YDrogen requested changes

2023-12-07 15:06 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +  return cocktail ? (
Ça serait plus lisible un petit `if` à la place de la ternaire je trouve

En 3 étapes : 
-> si ça charge : return null
-> si pas cocktail : return Navigate
-> return

2023-12-07 15:06 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +                style={{ strokeWidth: '3' }}
`stroke-4` et `strokeWidth` changent la même propriété, il faut retirer une des deux (sûrement celle qui n'est pas tailwind)

2023-12-07 15:43 UTC, Justicesvr commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +                style={{ strokeWidth: '3' }}
non la class tailwind ne marche pas j'ai laissé l'autre du coup!

2023-12-07 16:01 UTC, No3ml3 submitted a review, later dismissed

2023-12-07 16:03 UTC, jaalazard submitted a review, later dismissed
Oui.

2023-12-07 16:05 UTC, Cardamced submitted a review, later dismissed
C'est prop'.

2023-12-07 16:24 UTC, YDrogen requested changes

2023-12-07 16:24 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +                style={{ strokeWidth: '3' }}
Perdu, c'est pas le bon que t'as retiré
[`stroke-[3px]`](https://tailwindcss.com/docs/stroke-width#arbitrary-values)

2023-12-07 16:24 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +  }
Y'a un return en trop
validé par les collègues en plus... 🙄

2023-12-07 20:08 UTC, Cardamced commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +  }
Damned, celui-là je l'avais vu. Pis j'ai été dispersé.

2023-12-08 08:13 UTC, No3ml3 approved these changes

2023-12-08 08:14 UTC, jaalazard approved these changes

2023-12-08 08:39 UTC, YDrogen approved these changes

2023-12-08 08:39 UTC, merged