feat: a wonderful and responsive homepage
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #19
Opened 2023-12-11 18:18 UTC by jaalazard

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [x] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [x] My code follows the style guidelines of this project
- [x] I ran `bun run format`/`bun run lint` before commit
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where needed
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have updated `develop` and merged to my branch before submitting pull request
- [x] My pull request generate no conflicts with `develop` branch
- [x] I requested code review from other team members

## Frontend checklist:

- [x] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [x] My `Javascript` generate no new console errors
- [x] I tested my code cross browsers
- [x] My slice is pixel perfect for both desktop and mobile according to design
- [x] I conducted basic QA to assure all features are working
- [x] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-12 10:51 UTC, No3ml3 submitted a review, later dismissed

2023-12-12 10:54 UTC, Cardamced approved these changes, later dismissed
Parfait.

2023-12-12 16:01 UTC, YDrogen requested changes

2023-12-12 16:01 UTC, YDrogen commented on packages/frontend/web/src/components/home/CocktailsPart.tsx
> +      <div />
Pourquoi une `div` vide ?

2023-12-12 16:01 UTC, YDrogen commented on packages/frontend/web/src/components/home/CommunityPart.tsx
> +      <div />
partout ?

2023-12-12 16:01 UTC, YDrogen commented on packages/frontend/web/src/components/home/ShakeItPart.tsx
> +        <br />
Un `br` ???

2023-12-12 16:01 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
> +  const squares = [
Cette const n'a pas besoin d'être dans le component

2023-12-12 16:01 UTC, YDrogen commented on packages/frontend/web/tsconfig.json
Pas certain de ces modifs là

2023-12-12 16:01 UTC, YDrogen commented on packages/frontend/web/src/globals.css
J'ai pas déjà review ça dans une autre PR ?

2023-12-12 16:09 UTC, jaalazard commented on packages/frontend/web/src/components/home/CocktailsPart.tsx
> +      <div />
sinon : Fragments should contain more than one child - otherwise, there’s no need for a Fragment at all.

2023-12-12 16:09 UTC, jaalazard commented on packages/frontend/web/src/components/home/ShakeItPart.tsx
> +        <br />
Oui, tu as mieux ?

2023-12-12 16:11 UTC, jaalazard commented on packages/frontend/web/src/globals.css
J'ai créé de nouveaux clip-path, ceux déjà présents étaient md et lg

2023-12-12 16:12 UTC, jaalazard commented on packages/frontend/web/tsconfig.json
J'ai pas touché, je ne sais pas d'où ça sort, je supprime les modif ?

2023-12-13 08:16 UTC, No3ml3 approved these changes

2023-12-13 10:16 UTC, Cardamced approved these changes

2023-12-13 10:16 UTC, Justicesvr approved these changes

2023-12-13 10:16 UTC, Justicesvr commented on packages/frontend/web/src/pages/Home.tsx
beau travail pense peut être à te spécialiser dans le front

2023-12-13 11:18 UTC, YDrogen approved these changes

2023-12-13 11:18 UTC, merged