feat: back-end of glassPart
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #21
Opened 2023-12-13 10:49 UTC by No3ml3

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-13 10:51 UTC, jaalazard submitted a review, later dismissed

2023-12-13 11:25 UTC, Justicesvr submitted a review, later dismissed

2023-12-13 11:25 UTC, Justicesvr commented on packages/backend/api/src/glass.ts
random pour les verres ok

2023-12-13 14:06 UTC, YDrogen requested changes

2023-12-13 14:06 UTC, YDrogen commented on packages/backend/api/src/router.ts
> +router.use('/', glass);
Il vaut mieux mettre l'URL ici

2023-12-13 14:06 UTC, YDrogen commented on packages/backend/api/src/glass.ts
> +glass.get('/glass', async (req, res) => {
plutôt qu'ici

2023-12-13 14:06 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
> +  const url = `${import.meta.env.VITE_API_URL}/glass`;
À mettre hors du component

2023-12-13 14:06 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
> +  };
Pourquoi ne pas faire un fetch ici ? Plutôt que faire un state qui sert à faire croire au useEffect du useFetch que quelque chose à changé alors que non ?

2023-12-13 14:06 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-fetch.ts
> +  }, [url, ...deps]);
Très mauvaise idée, on ne contrôle pas ce qui va déclencher le useEffect

2023-12-13 14:06 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
> +  ) => void;
Comme pour le typage du `watch` "`UseFormWatch`", tu as aussi un type pour le `setValue`

2023-12-13 15:28 UTC, jaalazard submitted a review, later dismissed

2023-12-13 15:28 UTC, Justicesvr approved these changes

2023-12-13 15:29 UTC, Justicesvr approved these changes, later dismissed

2023-12-13 15:29 UTC, Justicesvr commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
plus de usefetch :(

2023-12-14 08:08 UTC, YDrogen requested changes

2023-12-14 08:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
> +  };
Je repose la question, pourquoi ne pas faire un simple fetch ici quand tu cliques sur le bouton ?
Pourquoi absolument vouloir passer par un `useEffect` ?

2023-12-14 10:39 UTC, No3ml3 commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
> +  };
consigne pas claire

2023-12-14 13:04 UTC, Justicesvr approved these changes, later dismissed

2023-12-14 13:04 UTC, Justicesvr commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
ok plus de useEffect

2023-12-14 13:05 UTC, jaalazard submitted a review, later dismissed

2023-12-14 14:51 UTC, YDrogen requested changes

2023-12-14 14:51 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
> +  };
Est-ce que tu comprends ce que tu fais ?
- Pourquoi il n'y a plus de `useEffect` ni de `useFetch` ? Comment est chargé le premier verre ?
- Pourquoi il y a un `AbortController` ? Il sert à quoi ici ?

2023-12-19 08:53 UTC, jaalazard submitted a review, later dismissed

2023-12-19 09:02 UTC, Cardamced approved these changes, later dismissed

2023-12-19 10:02 UTC, YDrogen requested changes

2023-12-19 10:02 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
Impec 👍 
Dernière question cependant : Pourquoi le backend envoi une array si tu n'utilise que le premier élément ? `data[0]` Pourquoi ne pas renvoyer qu'un seul élément ?

2023-12-19 10:32 UTC, jaalazard approved these changes

2023-12-19 10:33 UTC, Justicesvr approved these changes

2023-12-19 10:33 UTC, Justicesvr commented on packages/backend/api/src/glass.ts
le fameux select dans un select

2023-12-19 10:39 UTC, YDrogen approved these changes

2023-12-19 10:39 UTC, merged