Feature/cocktail details ingredients
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #22
Opened 2023-12-14 11:03 UTC by Justicesvr

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-14 20:08 UTC, Cardamced commented on package.json
Je pense que t'as pas besoin de cookie-parser, il est déjà sur dev depuis que je l'avais installé.

2023-12-14 20:11 UTC, Cardamced commented on packages/frontend/web/src/components/cocktail-detail/AddComment.tsx
Cool Framer-Motion ! :-)

2023-12-14 20:14 UTC, Cardamced commented on packages/frontend/web/src/components/cocktail-detail/CocktailComments.tsx
Je sais pas si ça passe les console.error ?

2023-12-14 20:16 UTC, Cardamced commented on packages/frontend/web/src/hooks/use-close-pop-up.ts
Cool ça, je vais peut-être le reprendre sur la modale Legal Notice & pour les cookies.

2023-12-14 21:56 UTC, Cardamced submitted a review, later dismissed
Good.

2023-12-15 08:45 UTC, jaalazard submitted a review, later dismissed
Nice

2023-12-15 10:02 UTC, jaalazard submitted a review, later dismissed
Encore plus nice !

2023-12-15 10:16 UTC, Cardamced approved these changes, later dismissed

2023-12-15 11:07 UTC, YDrogen requested changes

2023-12-15 11:07 UTC, YDrogen commented on packages/types/src/cocktail-detail.ts
Pourquoi les types des props sont ici ?

2023-12-15 11:07 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +                    {`, `}
Il ne devrait pas y avoir de virgules sur le dernier ingrédient, non ?

2023-12-15 11:07 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-close-pop-up.ts
> +export default function UseClosePopUp() {
Les hooks sont en camelCase

2023-12-15 11:07 UTC, YDrogen commented on packages/frontend/web/public/comment2.jpg
kebab-case pour les noms d'image

2023-12-15 11:07 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-close-pop-up.ts
> +  const popUp = useRef<HTMLDivElement>(null);
Pas génial le nom, un nom comme "ref" serait plus clair
Le type pourrait être un générique transmis, si on veut utiliser le hook sur autre chose qu'une div

2023-12-15 11:07 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-close-pop-up.ts
Belle idée ce hook 👍

2023-12-15 11:07 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/Comment.tsx
> +import UseClosePopUp from '@/hooks/use-close-pop-up';
à renommer en camelCase

2023-12-18 15:38 UTC, No3ml3 submitted a review, later dismissed

2023-12-18 15:52 UTC, jaalazard approved these changes, later dismissed

2023-12-19 11:06 UTC, No3ml3 approved these changes, later dismissed

2023-12-19 11:14 UTC, jaalazard submitted a review, later dismissed

2023-12-19 13:42 UTC, YDrogen requested changes

2023-12-19 13:42 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
Tu peux tout faire en une seule requête
[doc kysely](https://kysely.dev/docs/examples/SELECT/nested-array)
Ne supprime pas tout dès le début, tu pourras réutiliser les requêtes, elles sont ok 👌

2023-12-19 13:42 UTC, YDrogen commented on packages/backend/api/src/comment.ts
> +    if (!Boolean(commentsByUserIdCocktailId)) {
La variable `commentsByUserIdCocktailId` ici est transformée en boolean. Si elle n'existe pas / est vide alors ça devient `false`, `true` sinon.

Sachant qu'elle peut être `null` il est préférable de vérifier si la variable est égale à `null` plutôt, ça évite de rajouter une étape de transformation et rend le code un peu plus lisible

2023-12-19 13:42 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailComments.tsx
> +        ${import.meta.env.VITE_API_URL}/comment/${id}`,
Attention au saut de ligne ici !

2023-12-19 13:42 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/Comment.tsx
> +export default function Comment({ comments }: CommentsProps) {
Je pense que ça devrait être quelque chose comme ça plutôt :
```suggestion
interface Comment {
  content: string;
  score: number;
  rating_id: number;
  comment_id: number;
}

interface CommentProps {
  readonly comments: Comment[] | undefined;
}
export default function Comment({ comments }: CommentProps) {
```
Le suffixe `Props` faisant référence ici aux props du component, l'utiliser pour une interface utilisée ailleurs qu'en tant que props, ça porte à confusion.

2023-12-19 13:42 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/StarRating.tsx
> +export default function StarRating({ ratings }: CocktailCommentsProps) {
Même idée ici
Le nom de l'interface utilisée pour typer les props devrait être `NomDuComponentProps`

2023-12-19 13:42 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +};
Même idée ici par rapport aux noms, le `Props` porte à confusion avec les props du component alors que ces types ne sont pas utilisés pour typer des props

2023-12-19 14:54 UTC, Cardamced approved these changes, later dismissed

2023-12-20 14:56 UTC, No3ml3 approved these changes, later dismissed

2023-12-20 15:08 UTC, Cardamced approved these changes, later dismissed

2023-12-20 16:24 UTC, YDrogen requested changes

2023-12-20 16:24 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +            .where('recipe.cocktail_id', '=', Number.parseInt(id)),
Sur les `.where` imbriqués comme ça, tu peux utiliser `.whereRef` comme dans [la doc](https://kysely.dev/docs/examples/SELECT/nested-array) pour faire référence à la table parente (ici `cocktail`)

2023-12-20 16:24 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +type Ingredients = {
Attention aux pluriels, tu type 1 élément

2023-12-21 08:15 UTC, No3ml3 approved these changes, later dismissed

2023-12-21 08:23 UTC, jaalazard approved these changes, later dismissed

2023-12-21 11:12 UTC, YDrogen requested changes

2023-12-21 11:12 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +            .where('recipe.cocktail_id', '=', Number.parseInt(id)),
faut le faire

2023-12-21 11:12 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +            .where('cocktail_topping.cocktail_id', '=', Number.parseInt(id)),
sur les autres aussi

2023-12-21 13:44 UTC, jaalazard approved these changes
oui

2023-12-21 13:44 UTC, No3ml3 approved these changes

2023-12-21 13:47 UTC, YDrogen approved these changes

2023-12-21 13:47 UTC, merged