Feature/legal notice
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #24
Opened 2023-12-15 00:10 UTC by Cardamced

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [X] Frontend
- [  ] Backend
- [X] Other: .....

## General checklist:

- [X] My code follows the style guidelines of this project
- [X] I ran `bun run format`/`bun run lint` before commit
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation where needed
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] I have updated `develop` and merged to my branch before submitting pull request
- [X] My pull request generate no conflicts with `develop` branch
- [X] I requested code review from other team members

## Frontend checklist:

- [X] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [X] My `Javascript` generate no new console errors
- [X] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-15 08:45 UTC, jaalazard approved these changes, later dismissed
Nice ! Et responsive en plus !

2023-12-15 09:12 UTC, Justicesvr approved these changes, later dismissed

2023-12-15 09:12 UTC, Justicesvr commented on packages/frontend/web/src/pages/LegalModal.tsx
bien vu le local storage

2023-12-15 11:10 UTC, YDrogen requested changes

2023-12-15 11:10 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +    const hideModal: string | null = localStorage.getItem('hideLegalNotice');
le kebab-case convient bien pour les noms dans le localstorage

2023-12-15 11:10 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  return isModalShown ? (
un if est plus clair qu'une ternaire

2023-12-15 11:10 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +    <div className=' flex flex-col items-center text-black'>
espaces ?

2023-12-15 11:10 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +        <div className=' bg-light-green xxs:rounded-xl xxs:text-xl m-2 rounded-[30px] border-[5px] border-black p-4 font-bold transition-transform duration-500 ease-in-out hover:rotate-1 hover:scale-
espaces ?

2023-12-15 11:27 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +    const hideModal: string | null = localStorage.getItem('hideLegalNotice');
C'est corrigé.

2023-12-15 11:32 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  return isModalShown ? (
C'est corrigé.

2023-12-15 11:34 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +    <div className=' flex flex-col items-center text-black'>
Yep, c'est enlevé.

2023-12-15 11:34 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +        <div className=' bg-light-green xxs:rounded-xl xxs:text-xl m-2 rounded-[30px] border-[5px] border-black p-4 font-bold transition-transform duration-500 ease-in-out hover:rotate-1 hover:scale-
Corrections done.

2023-12-15 13:29 UTC, jaalazard approved these changes, later dismissed
mouais

2023-12-15 13:29 UTC, Justicesvr submitted a review, later dismissed

2023-12-18 08:10 UTC, YDrogen requested changes

2023-12-18 08:10 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  if (isModalShown) {
L'idée du `if` ici est de faire un return préventif
"si modal ne s'affiche pas, return null"
Ça évite de devoir encapsuler tout le JSX dans un if

2023-12-18 08:32 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  if (isModalShown) {
Hinhin, je note.

2023-12-18 08:36 UTC, jaalazard approved these changes

2023-12-18 08:52 UTC, Justicesvr approved these changes

2023-12-18 09:07 UTC, YDrogen approved these changes

2023-12-18 09:07 UTC, merged