Hotfix/style home page
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #26
Opened 2023-12-19 11:00 UTC by Justicesvr

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-19 11:14 UTC, jaalazard approved these changes, later dismissed

2023-12-20 08:50 UTC, No3ml3 submitted a review, later dismissed

2023-12-20 09:52 UTC, Cardamced approved these changes, later dismissed

2023-12-20 11:11 UTC, YDrogen requested changes

2023-12-20 11:11 UTC, YDrogen commented on packages/frontend/web/src/components/home/CommunityPart.tsx
> +        className='relative h-full w-full md:left-[-20px]  md:top-[-10px] lg:left-[-15px] lg:top-[5px] xl:left-[-35px] xl:top-[-5px]'
espace en trop

2023-12-20 11:11 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  .font-stroke-navbar {
le nom de la class ne doit pas mentionner là où elle sera utilisée

2023-12-20 14:57 UTC, No3ml3 approved these changes

2023-12-20 14:59 UTC, Cardamced approved these changes

2023-12-20 15:10 UTC, YDrogen approved these changes

2023-12-20 15:10 UTC, merged