Feature/other ingredient
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #27
Opened 2023-12-19 14:23 UTC by No3ml3

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-19 14:36 UTC, jaalazard approved these changes, later dismissed

2023-12-19 14:38 UTC, Justicesvr approved these changes, later dismissed

2023-12-19 14:38 UTC, Justicesvr commented on packages/frontend/web/src/components/form-cocktail/ingredients/ModalSearch.tsx
parfait la barre de navigation en modal

2023-12-20 14:15 UTC, YDrogen requested changes
Y'aurait pas 3 fois le même component ?
Est-ce un prank ?

2023-12-20 14:15 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
> +}
Pourquoi placer ces interfaces dans ce package ? Elles vont être réutilisées dans le backend ?

2023-12-20 14:15 UTC, YDrogen commented on packages/backend/api/src/ingredient.ts
> +});
Pourquoi mettre une condition ici ?

2023-12-20 16:23 UTC, jaalazard submitted a review, later dismissed

2023-12-20 16:25 UTC, Justicesvr submitted a review, later dismissed

2023-12-21 11:24 UTC, YDrogen requested changes

2023-12-21 11:24 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
> +        7;
?

2023-12-21 11:24 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
> +          7;
?

2023-12-21 11:24 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
> +          setValue('ingredient1', data[0]);
Pourquoi data[0] à chaque fois ?

2023-12-21 11:24 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
> +    }
A quoi sert ce switch ? Tu peux simplifier en 1 ligne

2023-12-21 11:24 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
> +      }
idem

2023-12-21 11:24 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +        )}
Y'a des boucles qui se perdent 😼

2023-12-21 14:40 UTC, Justicesvr approved these changes, later dismissed

2023-12-21 14:47 UTC, jaalazard approved these changes, later dismissed

2023-12-21 15:22 UTC, YDrogen requested changes

2023-12-21 15:22 UTC, YDrogen commented on packages/backend/api/src/ingredient.ts
> +  return res.json(ingredient[0]);
Pourquoi ne pas utiliser `.executeTakeFirst()` ?

2023-12-21 15:22 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +        );
- `isAll` ce n'est pas de l'anglais
- `({ ingredient })` la variable `ingredient` est déjà définie au dessus, ça porte à confusion, on ne sait pas la quelle est utilisée dans cette ligne
- `isThereNextIngredientsDefined` c'est toujours pas de l'anglais

2023-12-21 15:22 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
> +  ingredient,
C'est quoi la difference entre les 2 ?

2023-12-21 15:22 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +    }
Ça serait incroyable si en JS on pouvait utiliser un truc qui permet de réduire le code dupliqué... 🤔 💭 `une boucle.. ?`

2023-12-21 15:22 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +  const [show, setShow] = useState<number>(1);
C'est quoi ces chiffres au hasard ?

2023-12-21 15:22 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +  console.log(data);
?

2023-12-21 15:22 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
> +  ingredient3?: Pick<Ingredient, 'id' | 'name'>;
Si seulement il existait le concept de tableau en JS.... 🤔 
Attendez.. ! 💡

2023-12-21 16:01 UTC, No3ml3 commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +  const [show, setShow] = useState<number>(1);
les chiffres ne sont pas hasard ils definissent a quelle étape tu te trouve du form. il faut forcément montré la première bulle et setShow évolue en fonction du de ce qui est rempli

2023-12-21 16:02 UTC, No3ml3 commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +        );
j'en profte j'ai pas trop d'idee pour renommé isThereNextIngredientsDefined et isAllPreviousIngredientsDefined tu en as ?

2023-12-21 16:05 UTC, No3ml3 commented on packages/types/src/cocktail-form.ts
> +  ingredient3?: Pick<Ingredient, 'id' | 'name'>;
attends tu m'as fais changer des truc au niveau des ingrédient1 ingrédient2 ingrédient3 et maintenant il faut je recommence tout pour les foutre dans un tableau

2023-12-21 16:05 UTC, No3ml3 commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +  console.log(data);
okay my bad

2023-12-21 16:30 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +        );
`areAllPreviousIngredientsDefined`
`areAllNextIngredientsDefined`

2023-12-22 08:21 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
> +  ingredient3?: Pick<Ingredient, 'id' | 'name'>;
oui

2023-12-22 08:23 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +  const [show, setShow] = useState<number>(1);
Tu peux pas donner des noms en chaîne de caractères ?

2023-12-22 08:26 UTC, No3ml3 commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +  const [show, setShow] = useState<number>(1);
ça me permettait de ne montrer les div qu'à partir de l'index c'est pratique

                  <div
                    className={`
    ${show < index + 1 ? 'opacity-0' : 'opacity-100'} 
    absolute left-[3%] 
    top-0 flex h-screen w-[95%] flex-col items-center justify-center transition-opacity duration-500 sm:left-[10%] md:left-0 bg-[url('form-cocktail/bubble/bubble-${
      index + 1
    }.png')] bg-contain bg-center bg-no-repeat sm:w-[80%] md:h-full md:w-full md:bg-auto`}

2023-12-22 08:29 UTC, No3ml3 commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +        );
![Capture d’écran du 2023-12-22 09-28-54](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a/assets/107045925/b0fe7d0e-2d73-486c-80af-3d5ab467a2ac)

2023-12-22 08:34 UTC, No3ml3 commented on packages/types/src/cocktail-form.ts
> +  ingredient3?: Pick<Ingredient, 'id' | 'name'>;
donc avant que je fasse et que tu me dise de refaire il fraudais ça soit ainsi: ingredient?: Pick<Ingredient, 'id' | 'name'>[];

2023-12-22 11:00 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +        );
`isEach...`

2023-12-22 11:04 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
> +  ingredient3?: Pick<Ingredient, 'id' | 'name'>;
Au pluriel le nom de la prop; le reste yes
Je me disais que le fait de retirer 3x le même component t'aurais fait penser à modifier ça aussi

2023-12-22 11:05 UTC, No3ml3 commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +        );
okie merci

2024-01-04 08:52 UTC, Justicesvr submitted a review, later dismissed

2024-01-04 08:52 UTC, Justicesvr commented on packages/backend/api/src/ingredient.ts
>    return res.json([...ingredientsByIngredient, ...ingredient]);
ok pour la barre de recherche

2024-01-05 06:47 UTC, jaalazard submitted a review, later dismissed

2024-01-05 08:51 UTC, YDrogen requested changes

2024-01-05 08:51 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +        message: 'plesase choose 3 ingredients',
`plesase` 🤓

2024-01-05 08:51 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/ModalSearch.tsx
> +  readonly setActualingredient: (actualingredient: number) => void;
camelCase obligatoire

2024-01-05 08:51 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      typeof ingredientsValue[2].id == 'number'
Et si tu as 250 ingrédients, tu vas faire 250 conditions ?

2024-01-05 08:51 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +  setActualingredient,
camelCase

2024-01-05 08:51 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientToChoose.tsx
> +  setActualingredient,
idem

2024-01-05 10:44 UTC, Justicesvr submitted a review, later dismissed

2024-01-07 20:27 UTC, jaalazard approved these changes, later dismissed

2024-01-08 08:59 UTC, YDrogen submitted a review, later dismissed

2024-01-08 10:41 UTC, jaalazard approved these changes

2024-01-09 09:57 UTC, Cardamced approved these changes

2024-01-09 10:31 UTC, YDrogen approved these changes

2024-01-09 10:31 UTC, merged