feat: front of community page
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #28
Opened 2023-12-19 19:37 UTC by No3ml3

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-20 08:07 UTC, jaalazard submitted a review, later dismissed

2023-12-20 09:51 UTC, Cardamced submitted a review, later dismissed

2023-12-20 15:04 UTC, YDrogen requested changes
Pourquoi il y a des `.png` puis des `.webp` ?

2023-12-20 15:04 UTC, YDrogen commented on packages/frontend/web/src/pages/AllProfile.tsx
> +  const url = `${import.meta.env.VITE_API_URL}/user`;
Pourquoi c'est dans le component ?

2023-12-20 15:04 UTC, YDrogen commented on packages/frontend/web/src/pages/AllProfile.tsx
> +export default function AllProfile() {
Comment ça `AllProfile` ?

2023-12-20 15:04 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
> +    element: <AllProfile />,
Pourquoi ne pas appeler le component `CommunityPage` par exemple ??

2023-12-20 15:04 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
> +        'profil-picture-purple': '#9F13AF',
Sympa les noms mi français mi anglais

2023-12-20 16:27 UTC, jaalazard approved these changes, later dismissed
C'est beau

2023-12-20 20:42 UTC, Cardamced approved these changes

2023-12-21 11:29 UTC, YDrogen approved these changes

2023-12-21 11:29 UTC, YDrogen requested changes
.

2023-12-21 13:09 UTC, jaalazard approved these changes

2023-12-21 13:47 UTC, YDrogen approved these changes

2023-12-21 13:47 UTC, merged