Feature/navbar
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #31
Opened 2023-12-21 14:40 UTC by No3ml3

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-21 14:43 UTC, Justicesvr approved these changes, later dismissed

2023-12-21 14:43 UTC, Justicesvr commented on packages/frontend/web/src/components/Navbar.tsx
elle est trop bien notre navbar!!

2023-12-21 14:43 UTC, Justicesvr commented on packages/frontend/web/src/pages/Home.tsx
et oui les imports mal écris qui faisaient tout bugger

2023-12-21 14:46 UTC, jaalazard submitted a review, later dismissed

2023-12-22 13:30 UTC, jaalazard commented on packages/frontend/web/src/components/Navbar.tsx
> +      }
Pourquoi ?

2023-12-22 13:37 UTC, YDrogen requested changes

2023-12-22 13:37 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
> +        <CocktailsPart />
Pourquoi ? Les `<Link>` sont des balises `<a>`, pourquoi mettre un component dedans ?

2023-12-22 13:37 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +import { Link } from 'react-router-dom';
Ça tient sur une ligne

2023-12-22 13:37 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +      }
C'est en double là, non ? On pourrait le sortir hors du `switch`

2023-12-22 13:37 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +        </div>
Y'a des boucles qui se perdent

2023-12-22 13:37 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
> +    'really-dark-blue',
?

2023-12-22 14:18 UTC, No3ml3 commented on packages/frontend/web/src/pages/Home.tsx
> +        <CocktailsPart />
tu voudrais que je fasse exactement avec ça ? que j'entoure les composants  d'una balise button ? (et accessoirmeent casse absolument tout le style :cry:) que je mette les links a un autre endroit ?

2023-12-22 14:29 UTC, No3ml3 commented on packages/frontend/web/src/pages/Home.tsx
> +        <CocktailsPart />
en vrai j'ai replacer la div d'un de mes composant par button et ça n'a pas cassé tout le style est ce que ça te conviendrais ?

2023-12-22 14:57 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
> +        <CocktailsPart />
Non c'est ok, j'avais juste pas compris ce code

2023-12-30 14:53 UTC, jaalazard approved these changes, later dismissed

2024-01-03 08:10 UTC, Justicesvr submitted a review, later dismissed

2024-01-03 08:10 UTC, Justicesvr commented on packages/frontend/web/src/components/Navbar.tsx
plutot cool le switch dans un use effect

2024-01-04 09:45 UTC, YDrogen requested changes

2024-01-04 09:45 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +  lucid: React.ComponentType<IconProps>;
Il s'agit d'un component qui s'appelle `Icon`
Tu peux donc appeler la prop: `Icon`

2024-01-04 13:16 UTC, Justicesvr submitted a review, later dismissed

2024-01-05 06:46 UTC, jaalazard submitted a review, later dismissed

2024-01-05 09:16 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +  lucid: React.ComponentType<IconProps>;
Je parle de la **prop**, pas du type

2024-01-05 09:44 UTC, Cardamced approved these changes

2024-01-05 09:46 UTC, jaalazard approved these changes

2024-01-08 09:00 UTC, YDrogen approved these changes

2024-01-08 09:00 UTC, merged