Feature/post profile page
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #34
Opened 2024-01-09 09:31 UTC by No3ml3

a modal for update a user profile (pseudo, password, avatar, and bg color)

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-09 10:13 UTC, Cardamced submitted a review, later dismissed

2024-01-09 17:07 UTC, jaalazard submitted a review, later dismissed

2024-01-10 08:22 UTC, Justicesvr submitted a review, later dismissed

2024-01-10 16:26 UTC, YDrogen requested changes

2024-01-10 16:26 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +  email?: string;
Pas email du coup ?

2024-01-10 16:26 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +      }
Il faut inverser les 2 conditions, grosse faille de sécurité

2024-01-10 16:26 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +user.put('/:id', validateUpdateUser, async (req: Request, res: Response) => {
Grosse faille de sécurité, n'importe qui peut modifier n'importe quel utilisateur

2024-01-10 18:37 UTC, No3ml3 commented on packages/backend/api/src/user.ts
> +user.put('/:id', validateUpdateUser, async (req: Request, res: Response) => {
Oui je sais mais j'attends que l'authentification côté front passe pour faire en sorte que seul le user puisse être voir accès à se form sur sa page profile, et ainsi mettre toute cette sécurité en place

2024-01-11 09:34 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +user.put('/:id', validateUpdateUser, async (req: Request, res: Response) => {
Tu n'as pas besoin du front pour gérer la sécurité dans le back

2024-01-12 10:28 UTC, jaalazard commented on packages/backend/api/src/user.ts
> +    userId?: number; // Ajoutez la propriété `userId` comme nombre optionnel
ahahah le chat est passé par là !

2024-01-12 10:28 UTC, jaalazard approved these changes, later dismissed

2024-01-12 10:49 UTC, Justicesvr approved these changes, later dismissed

2024-01-12 10:49 UTC, Justicesvr commented on packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
cette partie est grave cool

2024-01-15 11:22 UTC, YDrogen requested changes

2024-01-15 11:22 UTC, YDrogen commented on packages/backend/api/src/middlewares/login-id-user.ts
> +}
? Qu'est-ce ? Que fait ces lignes ?
Vraie réponse attendue, pas de ChatGPT ni Copilot siouplé

2024-01-15 11:22 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
> +        element: <ConnectProfilePage />,
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a/assets/13053644/0ded4099-3bdd-4951-8de1-2b37d884a7ea)

2024-01-15 11:22 UTC, YDrogen commented on packages/frontend/web/src/pages/ConnectProfilePage.tsx
> +  const urlUser = `${import.meta.env.VITE_API_URL}/user/connect`;
Peut être sorti hors du component

2024-01-15 11:22 UTC, YDrogen commented on packages/backend/api/src/middlewares/login-id-user.ts
> +  let payload;
why?

2024-01-15 11:22 UTC, YDrogen commented on packages/backend/api/src/middlewares/login-id-user.ts
> +  next();
Tu peux le mettre dans le try à la suite

2024-01-15 11:22 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +  return db.transaction().execute(async (trx) => {
Y'a 3 fois la même requête SQL (ou presque) dans le fichier, il faut réduire ça

2024-01-15 11:22 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +user.get('/connect', loginIdUser, async (req, res) => {
Que fait cette route ?

2024-01-15 11:22 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +      res.json('true');
C'est pas du json ça

2024-01-15 11:22 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +          return res.json('wrong password');
ça non plus

2024-01-15 13:08 UTC, No3ml3 commented on packages/frontend/web/src/router.tsx
> +        element: <ConnectProfilePage />,
tu appellerai ça comment ? ConnectedProfilePage ?

2024-01-15 13:13 UTC, No3ml3 commented on packages/backend/api/src/middlewares/login-id-user.ts
> +  let payload;
vu que c pas du tsx et qu'il n'y a pas de state ..

2024-01-15 13:16 UTC, No3ml3 commented on packages/backend/api/src/user.ts
> +user.get('/connect', loginIdUser, async (req, res) => {
elle renvoie le profile du user qui est connecté (avec son email en prime)

2024-01-15 15:54 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
> +        element: <ConnectProfilePage />,
`ProfilePage`
(c'est l'actuelle `ProfilePage` qui ne devrait pas s'appeler comme ça, mais plutôt `PublicProfilePage`)

2024-01-15 15:56 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +user.get('/connect', loginIdUser, async (req, res) => {
Pourquoi pas `/profile` ? Ou `/` tout court ?

2024-01-16 09:18 UTC, jaalazard submitted a review, later dismissed

2024-01-16 12:57 UTC, Justicesvr submitted a review, later dismissed

2024-01-22 10:03 UTC, Justicesvr approved these changes, later dismissed

2024-01-22 10:30 UTC, jaalazard submitted a review, later dismissed

2024-01-22 15:11 UTC, Justicesvr approved these changes

2024-01-22 15:14 UTC, Justicesvr submitted a review, later dismissed

2024-01-22 15:40 UTC, jaalazard approved these changes, later dismissed

2024-01-23 09:39 UTC, YDrogen requested changes

2024-01-23 09:39 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +async function getUser(id: number, shouldEmail: boolean) {
`shouldEmail` ? Ça veut dire quoi ?
"devrait email" ?

2024-01-23 09:39 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +      res.json({ result: 'true' });
Comment ça `'true'` ?

2024-01-23 09:39 UTC, YDrogen commented on packages/backend/api/src/user.ts
Tu peux pas reprendre la structure du `auth.ts` ?
```typescript
return res.json({
  ok: true // ou false
  // message: 'un message',
  // error: 'message d\'erreur',
});
```

2024-01-23 09:39 UTC, YDrogen commented on packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
>          window.location.reload();
Comment ça `window.location.reload()` ?
Quel intérêt ?

2024-01-23 10:06 UTC, No3ml3 commented on packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
>          window.location.reload();
il met les donnée que l'utilisateur viens d'enregistrer en DB à jour sur la page profile.

2024-01-23 10:07 UTC, No3ml3 commented on packages/backend/api/src/user.ts
> +async function getUser(id: number, shouldEmail: boolean) {
traduction de mon langage : est ce qu'il y a besoin de l'email ? 
tu me conseil de l'appeler comment ?

2024-01-23 11:08 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +async function getUser(id: number, shouldEmail: boolean) {
`shouldSelectEmail`
`(devrait select email) ? (ajoute la colonne dans le select sql) : (rien)`

2024-01-23 11:09 UTC, YDrogen commented on packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
>          window.location.reload();
C'est faux, ça met rien à jour, ça recharge la page entière

2024-01-23 11:24 UTC, No3ml3 commented on packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
>          window.location.reload();
j'ai pas parler de mettre à jour, mais juste en backend si ça c bien enregistrer, que tout est okay ba je lui dit de rafraîchir la page. comme ca il me ferme la modal, et il me remplie les champs avec les nouvelles donnée qui viennent tout juste d'être enregistrer en back. Mais j'imagine que tu as quelque chose de mieux et une bonne raison si tu n'aime pas cette ligne. qui est ????

2024-01-23 18:29 UTC, jaalazard submitted a review, later dismissed

2024-01-24 08:19 UTC, Justicesvr approved these changes, later dismissed

2024-01-24 10:43 UTC, YDrogen requested changes

2024-01-24 10:43 UTC, YDrogen commented on packages/backend/api/src/user.ts
> +      res.json({ ok: 'true' });
Pourquoi `'true'` ?
`'true' !== true`

2024-01-24 10:43 UTC, YDrogen commented on packages/frontend/web/src/components/profile-page/modal/ModalForm.tsx
>        }
Roooh c'est de l'algo de base ça
`if / else`
Si ok = true, alors "..."
Sinon "..."
Ça évite de mettre ok === false dans 15 if

2024-01-24 10:43 UTC, YDrogen commented on packages/frontend/web/src/components/profile-page/modal/FormPart.tsx
> +interface FormPartPros {
`Pros` ?

2024-01-24 10:43 UTC, YDrogen commented on packages/frontend/web/src/components/profile-page/modal/FormPart.tsx
> +                    | 'confirmNewPassword',
```suggestion
                  input.name as keyof UserInfoForm
```
Un truc du genre devrait fonctionner

2024-01-24 10:43 UTC, YDrogen commented on packages/frontend/web/src/components/profile-page/modal/FormPart.tsx
> +      label: 'actual password',
current password

2024-01-24 11:18 UTC, Cardamced submitted a review, later dismissed

2024-01-24 11:18 UTC, Justicesvr approved these changes, later dismissed

2024-01-26 09:36 UTC, jaalazard approved these changes
Belle résolution de conflits

2024-01-29 09:13 UTC, Cardamced approved these changes
;-)

2024-01-29 10:55 UTC, YDrogen approved these changes

2024-01-29 10:55 UTC, merged