Feature/upload cocktail picture
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #36
Opened 2024-01-11 17:55 UTC by jaalazard

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-11 18:56 UTC, No3ml3 approved these changes, later dismissed

2024-01-11 21:47 UTC, Cardamced approved these changes, later dismissed

2024-01-12 10:36 UTC, YDrogen requested changes

2024-01-12 10:36 UTC, YDrogen commented on package.json
> +    "multer": "^1.4.5-lts.1"
Toujours pas ici les dépendances :(

2024-01-12 10:36 UTC, YDrogen commented on packages/backend/api/src/middlewares/multer-config.ts
> +    callback(null, name + Date.now() + '.' + extension);
Pas une bonne idée
Le name n'est pas fiable
Si le gars envoie la même image 2 fois au même moment, conflit, doublon
Tu peux utiliser [ça](https://nodejs.org/api/crypto.html#cryptorandomuuidoptions) pour générer des id uniques

2024-01-12 10:36 UTC, YDrogen commented on packages/backend/api/src/middlewares/multer-config.ts
> +  storage: storage,
```suggestion
  storage,
```
Tu peux raccourcir

2024-01-12 10:36 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +                  {'Formulaire envoyé avec succès !'}
Oh du français !

2024-01-12 10:36 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +  const [anecdote, setAnecdote] = useState('');
Soit les states liés au form ne servent à rien, soit c'est le hook `useForm` qui sert à rien
Y'a doublon là

2024-01-12 10:36 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +                  setUploadedImage(event.target.files);
Ton state étant au singulier, c'est ici que tu es censé set un seul fichier
`uploadedImage[0]` n'a pas de sens, c'est pas censé être un tableau

2024-01-12 10:36 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +      `.execute(db);
Très belle duplication de code 👍 

<details><summary>petit tip</summary>

```typescript
SET ${fields.map((f) => `${f.name} = ${f.value}`).join(', ')
```

</details>

2024-01-12 10:37 UTC, jaalazard commented on package.json
> +    "multer": "^1.4.5-lts.1"
A la racine du projet ?

2024-01-12 14:07 UTC, jaalazard commented on packages/backend/api/src/cocktail.ts
> +      `.execute(db);
Pas compris

2024-01-12 15:00 UTC, YDrogen commented on package.json
> +    "multer": "^1.4.5-lts.1"
Yes

2024-01-12 15:10 UTC, Justicesvr approved these changes, later dismissed

2024-01-12 15:11 UTC, Cardamced approved these changes, later dismissed
Je crois que c'est bô.

2024-01-15 11:28 UTC, YDrogen requested changes

2024-01-15 11:28 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
Tu l'utilises pas, si ?

2024-01-15 11:28 UTC, YDrogen commented on packages/backend/api/src/middlewares/multer-config.ts
> +      const uniqueName = buffer.toString('hex') + '_' + name + '.' + extension;
Presque, le hex généré peut techniquement ne pas être unique :(
Tu peux utiliser le UUID du module crypto qui lui est unique à chaque génération

2024-01-15 14:14 UTC, jaalazard commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
Non, je n'y arrive pas. Ça marchait très bien avant la "simplification" du code

2024-01-15 14:14 UTC, jaalazard commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
J'ai une erreur sql dans tous les cas en faisant comme ça

2024-01-15 15:50 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
Ouai ça doit être un truc comme ça, `... SET ${fieldsToUpdateString} WHERE ...`

2024-01-15 15:52 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
essaies de console.log `query.compile()`

2024-01-15 16:18 UTC, jaalazard commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
La propriété 'compile' n'existe pas sur le type 'string'.ts(2339)

2024-01-15 16:27 UTC, jaalazard commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
On me suggère de log query.toString(), ça donne : [backend:api] comp: UPDATE cocktail SET anecdote = 'yo' WHERE cocktail.id = 1; .... je vois pas ce qui est faux dans cette requête

2024-01-16 15:48 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
🤷‍♂️

2024-01-16 16:23 UTC, jaalazard commented on packages/backend/api/src/cocktail.ts
> +    .join(', ');
J'ai pas mieux. Tant pis du coup, pas d'upload

2024-01-17 08:12 UTC, No3ml3 approved these changes

2024-01-18 08:45 UTC, Cardamced approved these changes

2024-01-22 09:28 UTC, YDrogen approved these changes

2024-01-22 09:28 UTC, merged