Feature/database
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #4
Opened 2023-11-22 16:24 UTC by jaalazard

## Description

2 migrations file created : database structure and database data 

## Type of change

- [x ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [x ] Backend
- [ ] Other: .....

## General checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I ran `bun run format`/`bun run lint` before commit
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings
- [x ] I have updated `develop` and merged to my branch before submitting pull request
- [ x] My pull request generate no conflicts with `develop` branch
- [ x] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-22 20:26 UTC, No3ml3 approved these changes, later dismissed

2023-11-22 21:12 UTC, Justicesvr approved these changes, later dismissed

2023-11-22 21:14 UTC, Justicesvr commented
Good job, i'm waiting for you to explain the ORM to me tomorrow

2023-11-23 08:53 UTC, Cardamced approved these changes, later dismissed

2023-11-23 10:44 UTC, No3ml3 approved these changes, later dismissed

2023-11-23 10:46 UTC, Justicesvr submitted a review, later dismissed
Ok perfect and sorry for the confusion, it's not an ORM but a query builder :)

2023-11-23 10:52 UTC, Cardamced approved these changes, later dismissed
Top. RAS pour ma part.

2023-11-23 14:42 UTC, YDrogen requested changes
Il faut penser à typer la base de données dans `packages/types/src/database.ts`

2023-11-23 14:42 UTC, YDrogen commented on package.json
> +    "mysql2": "^3.6.5"
Nope

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +      id int AUTO_INCREMENT PRIMARY KEY,
unsigned

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +      id int AUTO_INCREMENT PRIMARY KEY,
pareil sur tous les INT qui ne peuvent pas être négatifs (comme les ID)

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +      id int AUTO_INCREMENT PRIMARY KEY,
Tu peux mettre tous les types en majuscules

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +      created_at datetime
idem

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +}
Pourquoi ne pas les mettre directement dans les create table ?

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122153904-database-data.ts
Les migrations sont censées être exécutées en production aussi, donc on évite les données de test (users)
Ok pour les données fixes de base comme les verres par ex.

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122153904-database-data.ts
> +  `.execute(db);
Ah ouai ?

2023-11-23 14:42 UTC, YDrogen commented on packages/types/src/database.ts
> +  created_at: Date;
A transformer en string, MySQL ne connait pas les objets Date (c'est du JS)

2023-11-23 14:42 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
Par défaut, toutes les colonnes sont nullables (sauf `primary key`, `non nullable`)
Il faut donc préciser pour chaque colonne

2023-11-23 14:42 UTC, YDrogen commented on packages/types/src/database.ts
Les champs optionnels :
❌ `name: string | null`
✅  `name?: string`

2023-11-23 15:01 UTC, jaalazard commented on packages/backend/migrations/src/migrations/20231122153904-database-data.ts
Ca nous permettait d'avoir des notes, des commentaires etc, temporairement, pour voir le rendu. Je trouvais ça pratique :'(

2023-11-23 15:01 UTC, jaalazard commented on packages/backend/migrations/src/migrations/20231122153904-database-data.ts
> +  `.execute(db);
Non ? Pas compris

2023-11-24 08:14 UTC, No3ml3 submitted a review, later dismissed

2023-11-24 09:37 UTC, Cardamced approved these changes, later dismissed
Impec.

2023-11-24 09:40 UTC, Justicesvr submitted a review, later dismissed
ok perfect

2023-11-24 09:58 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122153904-database-data.ts
> +  `.execute(db);
Un `up` insérait des données dans la bdd
Un `down` supprimait toutes les tables

Le but du `down` est d'annuler les changements apportés par le `up`
Il est <ins>obligatoire</ins> !

2023-11-24 09:59 UTC, YDrogen requested changes
commentaires au dessus

2023-11-24 10:25 UTC, Justicesvr approved these changes, later dismissed

2023-11-24 10:26 UTC, No3ml3 submitted a review, later dismissed

2023-11-24 10:26 UTC, Cardamced submitted a review, later dismissed
Ok.

2023-11-24 10:44 UTC, YDrogen requested changes
\+ commentaires plus haut

2023-11-24 10:44 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122153904-database-data.ts
> +  `.execute(db);
Ca marchera pas si tu `up` -> `down` -> `up` -> `down`
(c'est toujours pénible pour `down` un insert)

2023-11-24 11:07 UTC, No3ml3 approved these changes, later dismissed

2023-11-24 11:12 UTC, YDrogen requested changes
Il reste toujours le même commentaire + haut 🤷

2023-11-24 13:05 UTC, No3ml3 submitted a review, later dismissed

2023-11-24 13:07 UTC, Justicesvr submitted a review, later dismissed

2023-11-24 13:09 UTC, Cardamced submitted a review, later dismissed
Bô !

2023-11-24 13:21 UTC, YDrogen requested changes
Les migrations ne fonctionnent pas

2023-11-24 13:33 UTC, Justicesvr submitted a review, later dismissed

2023-11-24 13:34 UTC, No3ml3 submitted a review, later dismissed

2023-11-24 13:35 UTC, Cardamced submitted a review, later dismissed
Good.

2023-11-24 14:03 UTC, YDrogen requested changes

2023-11-24 14:03 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122143414-database-structure.ts
> +      author INT UNSIGNED,
Un cocktail peut ne pas avoir d'auteur ?

2023-11-24 14:03 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231122153904-database-data.ts
Dans le `down`, `DELETE FROM` ne réinitialise pas les ids
Donc la fois suivante où tu feras un `up`, les ids en dur ne seront plus bons
Lors de l'`insert`, tu peux récupérer les ids insérés pour les transmettre en variable dans les requêtes suivantes
(oui, c'est bien pénible de faire de l'automatisation d'`insert`)

2023-11-24 14:21 UTC, No3ml3 approved these changes

2023-11-24 14:22 UTC, Justicesvr approved these changes

2023-11-24 15:40 UTC, YDrogen approved these changes

2023-11-24 15:41 UTC, merged