Feature/shaker post
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #51
Opened 2024-01-22 10:40 UTC by No3ml3

## Description

partie backend pour enregistrer un cocktail - le code commenté fera l'objet d'un hotfix quand l'auth sera passé

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-22 11:07 UTC, jaalazard submitted a review, later dismissed

2024-01-22 13:34 UTC, Cardamced submitted a review, later dismissed
;-)

2024-01-22 15:20 UTC, Justicesvr submitted a review, later dismissed

2024-01-22 15:20 UTC, Justicesvr commented on packages/backend/api/src/cocktail.ts
> +
Parfait on va enfin pouvoir enregistrer le cocktail en base de donnée

2024-01-22 15:39 UTC, jaalazard submitted a review, later dismissed

2024-01-24 10:23 UTC, YDrogen requested changes

2024-01-24 10:23 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    const userId = 1;
Ah ? Y'a qu'un seul user ?

2024-01-24 10:23 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +// cocktailRouter.post('/add', loginIdUser, validateCocktailAdd, async (req: RequestWithUser, res: Response) => {
?

2024-01-24 10:23 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    );
Pourquoi ? Un Math.random() suffit

2024-01-24 10:23 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +        ];
Pourquoi on ajoute des ingrédients au pif quand on créé un cocktail ??

2024-01-24 10:23 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +
Je t'invite à regarder le `.reduce` en js

2024-01-24 10:23 UTC, YDrogen commented on packages/backend/api/src/middlewares/validate-cocktail-add.ts
> +}
Pourquoi ? T'as déjà un type Ingredient qui existe

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +                className='relative bottom-[-10px]  w-[100px] bg-white pl-1 pr-2 hover:cursor-pointer'
espace en trop

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +                className='w-[100px] w-full bg-white pl-1  pr-2 hover:cursor-pointer'
idem

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +                className='relative bottom-[-10px]  w-[100px] bg-white pl-1 pr-2 hover:cursor-pointer'
espace en trop

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +                className='w-[100px] w-full bg-white pl-1  pr-2 hover:cursor-pointer'
idem

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      navigate(`/details/${cocktailId}`);
Les erreurs de validation côté back ne sont pas gérées

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      navigate(`/details/${cocktailId}`);
Les erreurs de validation renvoyées du back ne sont pas gérées

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      navigate(`/details/${cocktailId}`);
Les erreurs de validation côté back ne sont pas gérées

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      navigate(`/details/${cocktailId}`);
Les erreurs de validation renvoyées du back ne sont pas gérées

2024-01-24 10:23 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      navigate(`/details/${cocktailId}`);
Les erreurs de validation renvoyées du back ne sont pas gérées

2024-01-24 10:33 UTC, No3ml3 commented on packages/backend/api/src/cocktail.ts
> +    const userId = 1;
j'attends l'authentification ... en attendant qu'elle passe ça enregistre au moins

2024-01-24 10:34 UTC, No3ml3 commented on packages/backend/api/src/cocktail.ts
> +
oui mais tu ne nous a pas donnée le droit de l'utiliser je me débrouille sans

2024-01-24 10:36 UTC, No3ml3 commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      navigate(`/details/${cocktailId}`);
comment tu as remis le même commentaire   5x ??

2024-01-24 10:45 UTC, No3ml3 commented on packages/backend/api/src/cocktail.ts
> +    );
oui mais je veux qu'il y ai plus de chance qu'il y est 0 ou 1 ingrédient que 5 par exemple

2024-01-24 10:55 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    const userId = 1;
L'authentification est déjà là ?

2024-01-24 10:56 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    );
```ts
const random = Math.random();
if(random <= 0.5) {
 // beaucoup de chance
 // 50% de chances
} else if (random <= 0.6) {
  // 10% de chances
} else {
  // 40% de chances
}
```

2024-01-24 10:57 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +
C'est un paramètre par défaut que je n'avais pas vu, vous pouvez désactiver la règle

2024-01-24 10:58 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      navigate(`/details/${cocktailId}`);
My bad, soucis d'internet au moment de review

2024-01-24 14:22 UTC, Cardamced submitted a review, later dismissed

2024-01-24 18:04 UTC, jaalazard approved these changes, later dismissed
RAS pour ma part

2024-01-26 13:40 UTC, jaalazard approved these changes, later dismissed

2024-01-26 16:32 UTC, Cardamced submitted a review, later dismissed

2024-01-29 11:01 UTC, YDrogen requested changes

2024-01-29 11:01 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    }
Si tu commences par les conditions où la valeur est la plus élevée tu peux simplifier
```suggestion
    let howMuchMoreIngredients = 0;

    if (random > 0.9) { // 10%
      howMuchMoreIngredients = 4;
    } else if (random > 0.8) { // 10%
      howMuchMoreIngredients = 3;
    } else if (random > 0.6) { // 20%
      howMuchMoreIngredients = 2;
    } else if (random > 0.4) { // 20%
      howMuchMoreIngredients = 1;
    } // pas besoin de else vu que par défaut c'est 0 / 40%
```

2024-01-29 11:01 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +              total_duration: initialData.totalDuration,
Tous les endroits où t'as rajouté `initialData.`
Je ne comprends pas l'intérêt
T'as testé ? T'as vu le résultat ? Est-ce que c'est vraiment ce que tu veux ?

2024-01-29 11:01 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +}
Depuis quand on fait des interfaces / types en camelCase ?
Prends ton temps en codant, sinon la PR va encore durer longtemps

2024-01-29 11:01 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    const createdAt = new Date();
Que fait cette const ici ? :(
Elle est toute seule dans son coin, la pauvre :(
Soit la rapprocher de là où elle sera utilisée, soit la supprimer et mettre le contenu directement là où elle est utilisée

2024-01-29 13:52 UTC, No3ml3 commented on packages/backend/api/src/cocktail.ts
> +              total_duration: initialData.totalDuration,
const initialData: InitialData = {
          totalQuantity: 0,
          totalkcal: 0,
          totalComplexity: 0,
          totalDuration: 0,
          quantity: [],
          kcal: [],
          complexity: [],
          duration: [],
          flavors: [],
          counts: {
            fruity: 0,
            spicy: 0,
            herbaceous: 0,
            floral: 0,
            woody: 0,
            bitter: 0,
            sweet: 0,
            salty: 0,
            sour: 0,
            neutral: 0,
          },
          maxCount: 0,
          maxItems: [],
        }; c'est par ce que ça appartient à cette objet, ça te dérange ?

2024-01-29 16:26 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +              total_duration: initialData.totalDuration,
J'ai bien compris que ça faisait référence à cet objet, mais du coup les valeurs sont `0` ou `undefined`
Tu n'es pas censée calculer les champs plutôt que de mettre 0 ?

2024-01-30 08:25 UTC, No3ml3 commented on packages/backend/api/src/cocktail.ts
> +              total_duration: initialData.totalDuration,
const data = allIngredients.reduce(
          (acc: InitialData, allIngredient: AllIngredient) => {
            const numberQuantity = Math.floor(Math.random() * 10 + 1);
            const numberComplexity = Math.floor(Math.random() * 10 + 1);
            const numberDuration = Math.floor(Math.random() * 10 + 1);
            acc.totalQuantity += numberQuantity;
            acc.totalComplexity += numberComplexity;
            acc.totalDuration += allIngredient.kcal;
            acc.totalkcal += numberDuration;
            acc.quantity.push(numberQuantity);
            acc.complexity.push(numberComplexity);
            acc.duration.push(numberDuration);
            acc.kcal.push(allIngredient.kcal);
            acc.flavors.push(allIngredient.flavour);

            // Update counts, maxCount, and maxItems
            acc.counts[allIngredient.flavour] =
              (acc.counts[allIngredient.flavour] || 0) + 1;
            if (acc.counts[allIngredient.flavour] > acc.maxCount) {
              acc.maxCount = acc.counts[allIngredient.flavour];
              acc.maxItems = [allIngredient.flavour];
            } else if (acc.counts[allIngredient.flavour] === acc.maxCount) {
              acc.maxItems.push(allIngredient.flavour);
            }

            return acc;
          },
          initialData,
        );

        const finalFlavour: Flavour =
          data.maxItems[Math.floor(Math.random() * data.maxItems.length)]; 

la je fais les maths voila resulats : 

![Capture d’écran du 2024-01-30 09-24-52](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a/assets/107045925/cad70721-2027-4d4e-b085-5fa5e1d1bad7)


mon ajout en DB avec post. je vois ou tu vois que ça fait 0 ou undefined ???

2024-01-30 10:52 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +              total_duration: initialData.totalDuration,
`initialData` n'est pas censé exister en fait, c'est tout le problème
Le reduce modifie initialData parce que tu l'utilises dedans. Ce n'est pas censé être le cas

2024-01-30 10:55 UTC, No3ml3 commented on packages/backend/api/src/cocktail.ts
> +              total_duration: initialData.totalDuration,
mais pourquoi vu que ça fonctionne je ne comprends pas le pb avec ça

2024-01-30 11:22 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +              total_duration: initialData.totalDuration,
Et alors ? C'est pas parce que ça fonctionne qu'il faut le faire
Juste le fait que je n'ai pas compris ce que faisait ton code est une raison suffisante pour indiquer qu'il y a un problème
Et je t'ai expliqué plus haut d'autres raisons

2024-01-31 09:06 UTC, jaalazard approved these changes, later dismissed

2024-01-31 09:38 UTC, Cardamced submitted a review, later dismissed
Parfait pour moi.

2024-02-06 10:05 UTC, jaalazard approved these changes

2024-02-06 13:34 UTC, Cardamced approved these changes

2024-02-06 13:35 UTC, jaalazard approved these changes

2024-02-07 15:43 UTC, YDrogen approved these changes

2024-02-07 15:44 UTC, merged