Feature/similar cocktail
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #53
Opened 2024-01-24 10:45 UTC by Justicesvr

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-24 10:48 UTC, jaalazard approved these changes, later dismissed

2024-01-24 10:52 UTC, No3ml3 submitted a review, later dismissed

2024-01-24 10:53 UTC, jaalazard submitted a review, later dismissed

2024-01-29 11:05 UTC, No3ml3 requested changes

2024-01-29 11:05 UTC, No3ml3 commented on packages/frontend/web/src/components/cocktail-detail/FireLevel.tsx
> +  }
code répété

2024-01-29 11:06 UTC, Cardamced requested changes
Moyennant la boucle pour les fire-level...

Edit : changements effectués me dit-on dans l'oreillette.

2024-01-29 11:14 UTC, No3ml3 approved these changes, later dismissed

2024-01-29 13:44 UTC, jaalazard submitted a review, later dismissed

2024-01-30 16:07 UTC, YDrogen requested changes

2024-01-30 16:07 UTC, YDrogen commented on packages/backend/api/src/cocktail.ts
> +    }
Erreur dans 100% des cas
`.send` et `.json` sont 2 fonctions qui envoient des réponses
Ici, tu `.send` "Upload successful!", donc tu envoie une réponse
Puis en fonction de s'il y a un fichier, soit tu `.json` une valeur, soit tu `.send` autre chose, ce qui dans les 2 cas envoie une autre réponse

Ce n'est pas possible d'envoyer 2 réponses, ça ne fonctionnera pas

2024-01-30 16:07 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/Comment.tsx
> +        <div className='m-3 h-[15rem] w-[18rem]  bg-[url("/comment.png")] bg-contain bg-no-repeat'>
espace en trop 🤓

2024-01-30 16:07 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailForm.tsx
> +                className='input ms-28 mt-2 w-full'
input ?

2024-01-30 16:07 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/FireLevel.tsx
> +  }
`let` INTERDITS en React, surtout dans les components !
Tu peux faire l'équivalent avec un habile calcul
`Math.min(Math.ceil(totalDegree / 15), 3)`

2024-01-30 16:07 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/FireLevel.tsx
> +  }
idem, les boucles `for` sont interdites ici ! 🚨 🚓 🚨

2024-01-30 16:07 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  }
Ah ok je comprends la classname 🤔 
Tu peux écrire `input[type='file']` (sans le `.`) pour appliquer à tous les inputs sans avoir à appliquer la class `input` à chaque fois si tu veux appliquer ce style partout
Si non, tu peux renommer la class pour que ça corresponde au contenu et pas juste "input"

2024-01-30 16:07 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/SimilarCocktail.tsx
> +                    src={` ${
espace en trop 🤔

2024-01-31 14:15 UTC, No3ml3 approved these changes

2024-02-02 09:04 UTC, jaalazard approved these changes
RIen ne me saute aux yeux, ça à l'air ok

2024-02-02 09:04 UTC, jaalazard approved these changes

2024-02-05 10:38 UTC, YDrogen approved these changes

2024-02-05 14:23 UTC, Cardamced approved these changes
Ok.

2024-02-05 16:03 UTC, merged