feat: admin
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #54
Opened 2024-01-24 17:57 UTC by jaalazard

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-24 18:03 UTC, jaalazard commented on packages/backend/api/src/admin.ts
@YDrogen Pour ne pas interférer avec les routes déjà construites (et donc ne pas casser le fameux array retourné avec un objet "data"), j'ai fait tout un router dédié à l'admin... Mauvaise idée ? 
Et autre question, puisque l'admin semble se lancer sur une application distincte, est-ce qu'il faut prévoir un accès sur l'application "principale" ? Un peu de mal à capter la division du projet dans ce cas précis.

2024-01-25 15:39 UTC, YDrogen commented on packages/backend/api/src/admin.ts
1. C'est pas une mauvaise idée, par contre, ça peut être bien de faire un dossier "admin" et de séparer un peu les routes, histoire que ce soit un peu plus lisible qu'un fichier de 541 lignes; Il faudrait aussi ajouter dans votre todo-list une authentification pour s'assurer que seule react admin peut accéder à la route admin. Exemple simple, tu ajoutes un Header dans chaque requête React Admin, et côté back, un middleware qui vérifie si le header est présent.
2. Pour les projets, pas besoin, c'est pas un pré-requis qu'il soit accessible de tous les côtés; Vous n'avez pas à le déployer sur le serveur (docker, ...) non plus. Vous pouvez, si vous voulez mais c'est pas obligatoire (et pas prioritaire non plus)

2024-01-25 18:01 UTC, jaalazard commented on packages/backend/api/src/admin.ts
Ok, j'ai divisé mon routeur alors. Et l'authentification admin fera l'objet d'une autre PR.

2024-01-26 08:34 UTC, Cardamced approved these changes, later dismissed
Top et complet ! Bravo.

2024-01-26 08:54 UTC, No3ml3 submitted a review, later dismissed

2024-01-31 15:34 UTC, YDrogen requested changes

2024-01-31 15:34 UTC, YDrogen commented on packages/frontend/admin/vite.config.ts
> +  console.log(BACKEND_HOST, BACKEND_PORT);
console log

2024-01-31 15:34 UTC, YDrogen commented on packages/frontend/admin/src/resources/create/ToppingCreate.tsx
> +      />{' '}
```suggestion
      />
```

2024-02-02 15:14 UTC, No3ml3 approved these changes

2024-02-05 15:05 UTC, Cardamced approved these changes
Top !

2024-02-05 15:08 UTC, Justicesvr approved these changes

2024-02-05 15:08 UTC, Justicesvr commented on .tools/tsconfig.json
> +  "extends": "../tsconfig.json",
pertinent cette virgule?

2024-02-05 16:24 UTC, YDrogen approved these changes

2024-02-05 16:25 UTC, merged