Feature/virgin
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #58
Opened 2024-01-26 15:20 UTC by Cardamced

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [X] Frontend
- [X] Backend
- [ ] Other: .....

## General checklist:

- [X] My code follows the style guidelines of this project
- [X] I ran `bun run format`/`bun run lint` before commit
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation where needed
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] I have updated `develop` and merged to my branch before submitting pull request
- [X] My pull request generate no conflicts with `develop` branch
- [X] I requested code review from other team members

## Frontend checklist:

- [X] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [X] My `Javascript` generate no new console errors
- [X] I tested my code cross browsers
- [X] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [X] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [X] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-27 18:08 UTC, No3ml3 submitted a review, later dismissed

2024-01-27 20:14 UTC, jaalazard submitted a review, later dismissed

2024-01-30 16:18 UTC, YDrogen requested changes

2024-01-30 16:18 UTC, YDrogen commented on packages/frontend/web/src/components/CheckBirthdate.tsx
> +import { useBirth } from '../contexts/BirthContext';
Pourquoi enlever les @ ?

2024-01-30 16:18 UTC, YDrogen commented on packages/frontend/web/src/components/CheckBirthdateAnimations.tsx
> +import { useBirth } from '../contexts/BirthContext';
whyyy

2024-01-30 16:18 UTC, YDrogen commented on packages/frontend/web/src/components/Layout/Layout.tsx
> +import { useAuth } from '../../contexts/AuthContext';
whyyyyyyyyy

2024-01-30 16:18 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
hein
y'a un problème là

2024-01-30 16:18 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/CocktailCard.tsx
Les cocktails avec alcools n'existent plus ?

2024-01-30 20:11 UTC, Cardamced commented on packages/frontend/web/src/components/CheckBirthdate.tsx
> +import { useBirth } from '../contexts/BirthContext';
Parce que ça générait des erreurs... enfin... ça soulignait en rouge.

2024-01-30 23:25 UTC, Cardamced commented on packages/frontend/web/src/router.tsx
Indeed... réglage de conflits foireux. Inadvertance toussa... je me couvre la tête de cendres froides (et les relecteurs aussi).

2024-01-30 23:26 UTC, Cardamced commented on packages/frontend/web/src/components/Layout/Layout.tsx
> +import { useAuth } from '../../contexts/AuthContext';
Idem... ça générait des erreurs. Maix peut-être mon vscode qui voyait la Vierge... ça m'a étonné aussi (les erreurs, pas la Vierge).

2024-01-30 23:26 UTC, Cardamced commented on packages/frontend/web/src/components/CheckBirthdateAnimations.tsx
> +import { useBirth } from '../contexts/BirthContext';
Passkeu.

2024-01-30 23:26 UTC, Cardamced commented on packages/frontend/web/src/components/cocktail-detail/CocktailCard.tsx
Vu avec Justine qui apparemment a fait des modifications. D'où la card plus nécessaire à cet endroit.

2024-01-31 09:17 UTC, No3ml3 approved these changes, later dismissed

2024-01-31 09:38 UTC, jaalazard approved these changes, later dismissed

2024-01-31 15:36 UTC, YDrogen requested changes

2024-01-31 15:36 UTC, YDrogen commented on packages/frontend/web/src/components/CheckBirthdate.tsx
Pourquoi toucher à ce component ? Ce n'est pas la PR pour

2024-01-31 15:40 UTC, Cardamced commented on packages/frontend/web/src/components/CheckBirthdate.tsx
Je suis bien d'accord et c'est ce que je commente ici ligne 22 : 
  // UseEffect commenté pour ne pas empêcher le scroll sur les pages avant le fix sur CheckBirthdate.
  
  Sinon ça empêche le scroll... Je dois faire le fix sur la PR qu'on a discuté --> régler Checkbirthdate et isUnderAge.

2024-01-31 15:59 UTC, YDrogen commented on packages/frontend/web/src/components/CheckBirthdate.tsx
C'est donc à régler dans une autre PR, pas celle-ci 🤓

2024-02-01 09:03 UTC, No3ml3 approved these changes, later dismissed

2024-02-05 13:41 UTC, jaalazard submitted a review, later dismissed

2024-02-07 09:34 UTC, No3ml3 submitted a review, later dismissed

2024-02-07 09:57 UTC, jaalazard approved these changes, later dismissed

2024-02-07 16:07 UTC, YDrogen requested changes

2024-02-07 16:07 UTC, YDrogen commented on packages/frontend/web/src/pages/Virgin.tsx
> +  }, []);
il manque la fonction cleanup

2024-02-08 09:02 UTC, Cardamced commented on packages/frontend/web/src/pages/Virgin.tsx
> +  }, []);
Corrigé.

2024-02-08 09:14 UTC, jaalazard approved these changes

2024-02-08 09:21 UTC, Justicesvr approved these changes

2024-02-08 09:26 UTC, YDrogen approved these changes

2024-02-08 09:26 UTC, merged