Feature/navbar login logout
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #59
Opened 2024-01-27 19:47 UTC by No3ml3

## Description

login logout on navbar

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-29 08:45 UTC, jaalazard approved these changes, later dismissed

2024-01-29 08:51 UTC, Cardamced submitted a review, later dismissed
Top !

2024-01-29 14:59 UTC, jaalazard approved these changes, later dismissed

2024-01-29 15:00 UTC, Cardamced approved these changes, later dismissed

2024-01-30 16:22 UTC, YDrogen requested changes

2024-01-30 16:22 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +                  {...(content.name === 'Logout' && { onClick: handleLogout })}
Oh c'est nouveau ça
Syntaxe pas très lisible
Qu'est-ce qui se passe ? Je suis redirigé sur le lien ou la fonction s'execute ?

2024-01-30 16:22 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +  console.log(navbarContent);
console log

2024-01-30 16:22 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +    }
T'es sûr de cette condition ?

2024-01-31 08:53 UTC, No3ml3 commented on packages/frontend/web/src/components/Navbar.tsx
> +                  {...(content.name === 'Logout' && { onClick: handleLogout })}
les deux ... je devrais faire une page logout ? et redirigé vers la page logout ? je ne peux pas avoir un fetch et une redirection vers home ??

2024-01-31 08:58 UTC, No3ml3 commented on packages/backend/api/src/auth.ts
> +    }
oui pk ?

2024-01-31 15:40 UTC, YDrogen submitted a review, later dismissed

2024-01-31 15:42 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +                  {...(content.name === 'Logout' && { onClick: handleLogout })}
Non, pas de page logout, ça sert à rien
Si, mais pas en même temps; comment tu sais que la fonction se fait bien avant de rediriger ?

2024-02-06 09:11 UTC, jaalazard approved these changes

2024-02-06 09:14 UTC, Justicesvr approved these changes

2024-02-07 16:08 UTC, YDrogen approved these changes

2024-02-07 16:08 UTC, merged