front end done
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #6
Opened 2023-11-29 09:16 UTC by No3ml3

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-29 09:26 UTC, jaalazard submitted a review, later dismissed
Ça me parait bien

2023-11-29 09:27 UTC, Cardamced approved these changes, later dismissed
Parfait.

2023-11-29 09:38 UTC, Justicesvr approved these changes, later dismissed
pareil beau travail !

2023-11-30 09:08 UTC, YDrogen requested changes
Les images seront utilisées seulement dans le formulaire cocktail ? (Elles sont toutes dans le dossier `form-cocktail`
Y aura-t-il qu'un seul "formulaire cocktail" ?
Noms d'image en kebab case ! `bubble-1.png`

2023-11-30 09:08 UTC, YDrogen commented on package.json
> +  "dependencies": {}
Pourquoi ?

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
Attention, il faut `extend` les couleurs, sinon ça remplace les couleurs de base de tailwind

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +              </li>
Ça peut être bien une boucle, non ?

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/public/form-cocktail/fire-level-empty.png
Cette image ne sert à rien, tu peux appliquer du CSS (saturation 0) pour retirer les couleurs de l'image en couleurs

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/public/form-cocktail/fire-level-full.png
Nom de l'image à changer

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/public/form-cocktail/polygon/polygon-blue.png
Y'aurait pas moyen de faire 1 svg avec cette forme et de changer la couleur avec du CSS ? Ca éviterait de faire 15 images pour chaque couleur

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +                className='w-[100px]  hover:cursor-pointer'
Pourquoi y'a deux espaces partout ?

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +}) {
A sortir dans une interface comme `GlassPart`

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +  readonly isOpen: boolean;
Pourquoi ce state n'est pas ici ?

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/IngredientsPart.tsx
> +}) {
interface

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
> +}) {
idem

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/NamePart.tsx
> +}) {
idem

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/NamePart.tsx
> +          {'Shake it !'}
En anglais il n'y a pas d'espace avant la ponctuation

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/NamePart.tsx
> +        {'Choose a name for your cocktail :'}
idem

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/NamePart.tsx
> +          </svg>
A sortir dans un component `components/icons/<NomDuSvg>Icon.tsx`

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/ToppingPart.tsx
> +}) {
interface

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  }
???

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  }
Pourquoi pas utiliser les class de Tailwind directement ?

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
Aucune validation de formulaire ?

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
Il y a beaucoup de répétition aussi dans ce fichier, y'a du code à simplifier !

2023-11-30 09:08 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
> +    path: 'add-cocktail',
Pourquoi `add-cocktail` ? Pas fou comme lien, ça fait très CRUD

2023-11-30 09:54 UTC, No3ml3 commented on packages/frontend/web/src/components/form-cocktail/AlcoholPart.tsx
> +  readonly isOpen: boolean;
je me sert de ce state dans une fonction qui est sur la page add-cocktail (quand tu as choisis ton alcool, il te setValue et te ferme la div dans la fonction 'handleClickAlcohol'

2023-12-01 14:42 UTC, jaalazard approved these changes, later dismissed

2023-12-01 14:45 UTC, Justicesvr approved these changes

2023-12-01 14:45 UTC, Cardamced submitted a review, later dismissed
Top.

2023-12-01 14:51 UTC, Justicesvr approved these changes, later dismissed

2023-12-01 14:51 UTC, Justicesvr commented on packages/types/src/cocktail-form.ts
Grosse PR avec beaucoup de travail entre la gestion du responsive le formulaire et les typages!

2023-12-04 08:35 UTC, YDrogen requested changes
Pas de validation de formulaire ?
([zod](https://zod.dev/))

2023-12-04 08:35 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
> +export * from './database';
Pourquoi ?

2023-12-04 08:35 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
C'est une bonne pratique de préciser qu'il s'agit de props dans le nom de l'interface quand c'est le cas, ça évite les doublons avec les noms de component
`LevelPartProps` pour le component `LevelPart` par exemple

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
> +  },
J'me souviens pas d'une site où y'a écrit "formulaire" dans le lien quand j'arrive sur un formulaire 🤔

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      myComponent: (
`myComponent` ?

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +      square: {
C'est quoi ça `square` ?

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +import type { CocktailForm } from '@app/types/src/cocktail-form';
On importe pas depuis `src`
-> C'est mal exporté

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  }
?

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/globals.css
Les sauts de ligne entre les classes c'est bien aussi

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/GlassPart.tsx
> +      <div className='sm: relative bottom-[5%] flex md:bottom-[12%]'>
`sm: ` ?

2023-12-04 08:35 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
???
Pourquoi utiliser `order` quand il suffit juste de les mettre dans le bon ordre ??
\+ ça va dans une boucle

2023-12-04 13:36 UTC, jaalazard submitted a review, later dismissed
Ça me parait bien

2023-12-04 13:42 UTC, Justicesvr approved these changes, later dismissed

2023-12-04 13:42 UTC, Justicesvr commented on packages/frontend/web/src/globals.css
effectivement c'est mieux d'importer un seul svg polygon et lui attribuer la couleur en fonction des besoins

2023-12-04 13:42 UTC, Cardamced commented on packages/frontend/web/src/components/form-cocktail/NamePart.tsx
Petite coquille à "handleErroSubmit". Est-ce que ça ne devrait pas être "HandleErrorSubmit" ?

2023-12-04 13:44 UTC, Cardamced requested changes
Juste une éventuelle petite coquille, j'ai mis les lignes précises. ;-)

2023-12-04 13:51 UTC, Justicesvr submitted a review, later dismissed

2023-12-04 13:58 UTC, YDrogen requested changes

2023-12-04 13:58 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
> +const myLevel = [3, 2, 1];
`myLevel` ? C'est quoi ton level ?

2023-12-04 13:58 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  }
non, regardez la doc

2023-12-04 13:58 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
les sauts de ligne

2023-12-04 13:58 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +        {squares.map((div, index) => (
```suggestion
        {squares.map((div, index) => (
```
Pourquoi `div` ? Ca porte à confusion avec la balise `div`

2023-12-04 13:58 UTC, YDrogen commented on packages/frontend/web/package.json
> +    "tailwindcss-filters": "^3.0.0"
Pourquoi faire ?

2023-12-04 14:15 UTC, jaalazard submitted a review, later dismissed
Well done !

2023-12-04 14:16 UTC, Justicesvr approved these changes, later dismissed

2023-12-04 14:44 UTC, Cardamced submitted a review, later dismissed
Top !

2023-12-05 08:37 UTC, YDrogen requested changes

2023-12-05 08:37 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
> +        ...require('tailwindcss/defaultTheme').fontFamily.sans,
😬

2023-12-05 08:53 UTC, jaalazard approved these changes
Bien vu ce filter sans plugin !

2023-12-05 08:54 UTC, Cardamced approved these changes
Très bien.

2023-12-05 09:06 UTC, YDrogen approved these changes

2023-12-05 09:06 UTC, merged