feature/legal-modal-2
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #61
Opened 2024-01-29 09:43 UTC by Cardamced

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [X] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [X] My code follows the style guidelines of this project
- [X] I ran `bun run format`/`bun run lint` before commit
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation where needed
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] I have updated `develop` and merged to my branch before submitting pull request
- [X] My pull request generate no conflicts with `develop` branch
- [X] I requested code review from other team members

## Frontend checklist:

- [X] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [X] My `Javascript` generate no new console errors
- [X] I tested my code cross browsers
- [X] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [X] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-29 10:10 UTC, No3ml3 submitted a review, later dismissed

2024-01-29 11:02 UTC, Justicesvr submitted a review, later dismissed

2024-01-30 11:27 UTC, YDrogen requested changes
Le nom de la branche ?
Pourquoi hotfix ? C'est un problème qui se trouve sur main ?
Pourquoi du pascal case ?

2024-01-30 11:27 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  const now: Date = new Date();
Peut être sorti du component

2024-01-30 23:22 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  const now: Date = new Date();
Done. Ça va finir par rentrer ces const date de portée générale...

2024-01-30 23:22 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  const now: Date = new Date();
Le nom de la branche c'est corrigé.

2024-01-31 08:10 UTC, No3ml3 approved these changes

2024-01-31 09:06 UTC, jaalazard approved these changes

2024-01-31 15:46 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  const now: Date = new Date();
J'attends la bonne PR du coup

2024-01-31 15:50 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  const now: Date = new Date();
Je ne suis pas sûr de bien comprendre... Je ferme celle-ci ; je recrée une PR avec un nom correct ? Parce que l'autre feature/legalmodal existait déjà et avait été mergée. Mais peut-être que je comprends mal.

2024-01-31 15:59 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  const now: Date = new Date();
Je ne vais pas merge cette PR, la branche n'a pas le bon nom

2024-01-31 16:00 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
> +  const now: Date = new Date();
Ben ça je l'avais compris ^^

2024-02-06 13:49 UTC, closed without merging