Feat/404page
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #62
Opened 2024-01-29 13:29 UTC by Cardamced

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [X] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [X] My code follows the style guidelines of this project
- [X] I ran `bun run format`/`bun run lint` before commit
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation where needed
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] I have updated `develop` and merged to my branch before submitting pull request
- [X] My pull request generate no conflicts with `develop` branch
- [X] I requested code review from other team members

## Frontend checklist:

- [X] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [X] My `Javascript` generate no new console errors
- [X] I tested my code cross browsers
- [X] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [X] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-29 13:37 UTC, jaalazard approved these changes

2024-01-29 13:59 UTC, No3ml3 approved these changes

2024-01-30 11:28 UTC, YDrogen requested changes
Merci de ne pas désactiver husky, tu te retrouve avec des problèmes dans le nom des branches

2024-01-30 11:28 UTC, YDrogen commented on packages/frontend/web/src/pages/LegalModal.tsx
Pourquoi ces modifs sont dans 2 PR différentes ?

2024-01-30 11:31 UTC, Cardamced commented on packages/frontend/web/src/pages/LegalModal.tsx
Aucune idée... j'ai pourtant recommencé depuis develop et tiré une branche. Je vais recommencer.

2024-01-30 22:33 UTC, closed without merging