Feature/no alcohol shaker
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #64
Opened 2024-01-30 09:45 UTC by No3ml3

## Description

possibility to create a cocktail without alcohol in shaker

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-30 10:01 UTC, Cardamced submitted a review, later dismissed
Cool. J'aurai besoin de le relire encore et encore pour bien m'en imprégner. J'ai appris des trucs.

2024-01-30 10:06 UTC, jaalazard approved these changes, later dismissed

2024-01-31 15:57 UTC, YDrogen requested changes

2024-01-31 15:57 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20240127200850-type-ingredient.ts
> +      MODIFY  family ENUM('water', 'alcohol', 'juice', 'soda', 'syrup', 'bitter', 'fruit', 'vegetable', 'herb', 'spice', 'sauce', 'milk', 'cream', 'condiment', 'meat', 'seafood', 'other', 'softdrink'
double espace

2024-01-31 15:57 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
> +          className='peer sr-only'
À quoi sert `sr-only` ?

2024-01-31 15:57 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/Softdrinks.tsx
> +  const url = `${import.meta.env.VITE_API_URL}/ingredient/softdrinks`;
à sortir hors du component

2024-01-31 15:57 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/Softdrinks.tsx
> +          className='peer sr-only'
idem

2024-01-31 15:57 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/Softdrinks.tsx
> +        <div className="peer h-6 w-11 rounded-full bg-gray-200 after:absolute after:start-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-whit
C'est quelle IA qui a écrit ce code ? Copilot ? ChatGPT ?

2024-01-31 15:57 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/Syrup.tsx
> +  const url = `${import.meta.env.VITE_API_URL}/ingredient/syrup`;
idem

2024-01-31 15:57 UTC, YDrogen commented on packages/types/src/cocktail-form.ts
> +export interface SoftdrinksProps {
camelcase

2024-02-06 08:59 UTC, No3ml3 commented on packages/frontend/web/src/components/form-cocktail/LevelPart.tsx
> +          className='peer sr-only'
la doc que j'ai utilisé et non pas chat gpt copilot ou corsel 
![Capture d’écran du 2024-02-06 09-57-51](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a/assets/107045925/f14845e5-b730-40a0-82e1-88b314431b9c)
![Capture d’écran du 2024-02-06 09-57-40](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a/assets/107045925/bfb8c211-ea73-482f-83c0-c9e800b797bb)
et je te laisse voir la différence avec et sans le sr-only

2024-02-06 09:28 UTC, jaalazard approved these changes, later dismissed
Rien ne me choque, c'est bueno

2024-02-06 13:29 UTC, Cardamced approved these changes, later dismissed

2024-02-07 16:11 UTC, YDrogen approved these changes, later dismissed

2024-02-12 11:21 UTC, jaalazard submitted a review, later dismissed

2024-02-12 11:25 UTC, Justicesvr submitted a review, later dismissed

2024-02-12 11:28 UTC, Cardamced submitted a review, later dismissed

2024-02-13 16:13 UTC, YDrogen requested changes

2024-02-13 16:13 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +        credentials: 'include',
plus b'soin

2024-02-13 16:13 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
> +        credentials: 'include',
plus b'soin

2024-02-13 16:13 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
Trop de code dans ce fichier, à sortir dans des composants

2024-02-14 09:28 UTC, Cardamced approved these changes, later dismissed

2024-02-14 09:46 UTC, jaalazard approved these changes, later dismissed

2024-02-14 13:09 UTC, jaalazard approved these changes, later dismissed

2024-02-14 13:14 UTC, Justicesvr submitted a review, later dismissed

2024-02-15 08:16 UTC, No3ml3 commented on packages/frontend/web/src/pages/AddCocktail.tsx
j'imagine que tu m'as remis en change requested car tu trouves que je n'ai pas assez découpé cette page. Mais maintenant il ne reste plus grand chose que je trouve sortable.

2024-02-15 10:01 UTC, YDrogen requested changes

2024-02-15 10:01 UTC, YDrogen commented on packages/frontend/web/src/pages/AddCocktail.tsx
Y'a plein de choses possibles
1) Enlever les props liées au `useForm` et utiliser `useFormContext` dans ces composants à la place
2) Sortir les gros blocs (squaresWithAlcohol, ..) dans d'autres fichiers sous forme de fonction
```ts
getSquares({
  withAlcohol: true, // ou false
  // autres params éventuels
})
```
Avec ces 2 modifs, tu gagnes 200 lignes dans ce fichier

2024-02-15 11:16 UTC, No3ml3 commented
Bon, j'ai seulement fait la deuxième tâche, tu sais, celle où j'ai déplacé les gros morceaux de code dans d'autres fichiers sous forme de fonctions (squaresWithAlcohol, etc.). J'ai fait ça parce que je n'étais pas sûr si c'était bien ce que tu attendais.

Pour la première tâche, l'idée était de virer les props liées à useForm et d'utiliser useFormContext à la place. J'ai choisi de ne pas le faire, car si je le faisais, la page AddCocktail serait complètement vide.

Personnellement, je pense que la façon dont c'est organisé actuellement est cool : AddCocktail gère le côté hookForm, et getSquares s'occupe des composants. Ajouter une couche de division supplémentaire me semble inutile, mais bon, c'est toi qui vois. Je te dis simplement pourquoi je n'ai pas fait toutes les tâches.

2024-02-15 11:18 UTC, jaalazard approved these changes, later dismissed

2024-02-15 11:25 UTC, Justicesvr approved these changes, later dismissed

2024-02-20 11:18 UTC, YDrogen commented
> Pour la première tâche, l'idée était de virer les props liées à useForm et d'utiliser useFormContext à la place. J'ai choisi de ne pas le faire, car si je le faisais, la page AddCocktail serait complètement vide.

> **car si je le faisais, la page AddCocktail serait complètement vide.**

C'est bien, non ? Un fichier simple et facile à lire d'un rapide coup d'oeil

2024-02-20 11:21 UTC, No3ml3 commented
je trouve que ça sert a rien ça fait des milliard de props pour rien

2024-02-20 11:28 UTC, YDrogen commented
Nous sommes d'accord. Dans la version actuelle, il y a "des milliards de props" ce qui rend le code difficile à lire et à comprendre. Utiliser `useFormContext` rendrait le code plus lisible.

2024-02-20 13:39 UTC, jaalazard submitted a review, later dismissed

2024-02-20 13:43 UTC, Cardamced submitted a review, later dismissed

2024-02-20 14:11 UTC, Justicesvr submitted a review, later dismissed

2024-02-20 16:12 UTC, YDrogen requested changes

2024-02-20 16:12 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/MainForm.tsx
> +  };
Pourquoi c'est dans ce fichier et pas chaque bloc dans chaque "square" ?? C'est tout l'intérêt du `FormProvider`

2024-02-21 09:07 UTC, jaalazard submitted a review, later dismissed

2024-02-21 09:11 UTC, Justicesvr submitted a review, later dismissed

2024-02-21 10:21 UTC, YDrogen requested changes

2024-02-21 10:21 UTC, YDrogen commented on packages/frontend/web/src/components/form-cocktail/GetSquares.tsx
> +  } = useFormContext();
C'est seulement utilisé pour envoyer dans les props, donc pas utile dans ce fichier, tu peux utiliser `useFormContext` dans les composants en question
Appliques toi sur ces changements stp, ça fait 3 fois que je demande la même chose

2024-02-21 13:35 UTC, jaalazard approved these changes

2024-02-21 13:37 UTC, Justicesvr approved these changes

2024-02-26 08:05 UTC, YDrogen approved these changes

2024-02-26 08:06 UTC, merged