adding some data & pictures
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #65
Opened 2024-01-30 11:04 UTC by jaalazard

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-30 11:13 UTC, Cardamced submitted a review, later dismissed
Top.

2024-01-30 11:15 UTC, No3ml3 approved these changes, later dismissed

2024-01-30 11:17 UTC, Cardamced submitted a review, later dismissed
Yop !

2024-01-30 16:26 UTC, YDrogen requested changes

2024-01-30 16:26 UTC, YDrogen commented on package.json
> +    "react-refresh": "^0.14.0"
?

2024-01-31 08:09 UTC, jaalazard commented on package.json
> +    "react-refresh": "^0.14.0"
je ne pouvais pas bun run dev sans ça :(

2024-01-31 08:12 UTC, No3ml3 approved these changes

2024-01-31 08:13 UTC, Justicesvr approved these changes

2024-01-31 08:13 UTC, Cardamced approved these changes
Yep !

2024-01-31 16:00 UTC, YDrogen approved these changes

2024-01-31 16:01 UTC, merged