cocktails details page, only front part
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #7
Opened 2023-11-29 09:21 UTC by Justicesvr

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-29 09:28 UTC, jaalazard approved these changes, later dismissed
Ça me parait bien

2023-11-29 09:29 UTC, Cardamced submitted a review, later dismissed
Ok. Juste à régler les conflits. Peut-être en faisant bun i au moment de push.

2023-11-29 09:29 UTC, No3ml3 submitted a review, later dismissed

2023-11-29 09:38 UTC, No3ml3 submitted a review, later dismissed

2023-11-29 09:39 UTC, jaalazard approved these changes, later dismissed

2023-12-01 09:24 UTC, YDrogen requested changes

2023-12-01 09:24 UTC, YDrogen commented on package.json
> +  "dependencies": {}
sert à rien du coup

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/public/cocktail-placeholder.png
Très belle image (beaucoup trop grosse)

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/public/star-yellow.png
Pas possible de l'avoir en svg et changer la couleur avec du CSS ?

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailCard.tsx
> +            <img src='star.png' className='h-[1.7rem] w-[1.7rem]' />
Tu peux faire une boucle

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailComments.tsx
> +            <img src='star.png' className='h-[1.7rem] w-[1.7rem]' />
idem

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailComments.tsx
> +            />
idem

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailForm.tsx
> +            <p className='uppercase'>{`shake it !`}</p>
```suggestion
            <p className='uppercase'>{`shake it!`}</p>
```
Pas d'espace avant la ponctuation en anglais

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailForm.tsx
> +        <h3 className='mt-6 text-center uppercase'>{`change me !!!`}</h3>
idem

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +  };
à sortir hors du component

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +  };
pareil

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +  };
Pourquoi ne pas utiliser le hook `useDisclosure` ?

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/components/Navbar.tsx
> +              </motion.div>
Ca peut être dans une boucle ça, y'a beaucoup de répétition

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  }
https://tailwindcss.com/docs/font-family

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +      0 0 3px #0e0f0f;
On peut pas en enlever quelques uns ? :(
Ça fait beaucoup là non ?

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +              <img src='star.png' className='h-[1.7rem] w-[1.7rem]' />
Boucle possible

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +              <img src='star.png' className='h-[1.7rem] w-[1.7rem]' />
idem

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
> +      <span className='text-light stroke-font'>{'Coucou'}</span>
Pourquoi ?

2023-12-01 09:24 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
Attention, des modifs sont demandées à ce sujet dans une autre PR, ça va créer des conflits

2023-12-01 09:40 UTC, Justicesvr commented on packages/frontend/web/src/globals.css
> +      0 0 3px #0e0f0f;
ba non c'est tout l'intéret de la police on ne peut pas faire autrement

2023-12-01 15:10 UTC, Justicesvr commented on packages/frontend/web/src/pages/Home.tsx
> +      <span className='text-light stroke-font'>{'Coucou'}</span>
c'etait pour tester si tailwind fonctionnais lors de la premier PR

2023-12-01 15:20 UTC, Justicesvr commented on packages/frontend/web/public/star-yellow.png
si il faudrait une autre étoile du coup

2023-12-01 15:33 UTC, No3ml3 commented
tu as des conflicts

2023-12-04 08:15 UTC, No3ml3 submitted a review, later dismissed

2023-12-04 08:17 UTC, jaalazard submitted a review, later dismissed

2023-12-04 08:21 UTC, Cardamced submitted a review, later dismissed

2023-12-04 08:59 UTC, YDrogen requested changes

2023-12-04 08:59 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailCard.tsx
> +  }
Peut être sorti hors du component

2023-12-04 08:59 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailComments.tsx
> +  }
Ça peut être sorti dans un component même 👀

2023-12-04 08:59 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +  }
👀

2023-12-04 08:59 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
> +      <span>{'Coucou'}</span>
Pourquoi retirer ce text rouge ? :(

2023-12-04 09:35 UTC, Justicesvr commented on packages/frontend/web/src/pages/Home.tsx
> +      <span>{'Coucou'}</span>
ba je ne sais pas tu m'as demandé pourquoi j'avais mis ça la dernière fois

2023-12-04 13:37 UTC, jaalazard approved these changes, later dismissed
Ça me parait bien

2023-12-04 13:38 UTC, No3ml3 submitted a review, later dismissed

2023-12-04 18:30 UTC, Cardamced submitted a review, later dismissed
Top ;-)

2023-12-05 09:05 UTC, YDrogen requested changes

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailCard.tsx
> +      <div className='border-dark bg-pastel-brown absolute -top-6 left-6  m-auto my-20 h-[21rem] w-[18rem] rounded-sm border-[3px]' />
2 espaces

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailCard.tsx
> +            {' '}
Sert à rien ?

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/components/CocktailForm.tsx
> +        <div className='bg-light-beige border-dark m-auto  mt-10 h-[60%] w-[85%] rounded-sm border-2' />
2 espaces

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/components/CommentComponent.tsx
> +}) => {
Les components sont en `PascalCase`
Sous forme de `function`
et ne doivent pas contenir `Component` dans le nom

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/components/StarIndex.tsx
idem
Pourquoi `Index` ?

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/components/StarRating.tsx
idem

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +              {' '}
sert à rien ?

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/src/pages/CocktailsDetails.tsx
> +              {' '}
sert à rien ?

2023-12-05 09:05 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
> +        ...require('tailwindcss/defaultTheme').fontFamily.sans,
peut se faire sous forme d'`import`

2023-12-05 10:10 UTC, No3ml3 approved these changes, later dismissed

2023-12-05 11:21 UTC, YDrogen requested changes

2023-12-05 11:21 UTC, YDrogen commented on packages/frontend/web/src/components/Comment.tsx
> +  return <div className='flex w-full flex-wrap p-2'>{comments}</div>;
Pourquoi ne pas mettre le `Array.from` directement ici dans le return ?

2023-12-05 11:21 UTC, YDrogen commented on packages/frontend/web/src/components/Star.tsx
> +      key={index}
Pas besoin de `key`, tu n'es pas dans un map

2023-12-05 11:21 UTC, YDrogen commented on packages/frontend/web/src/components/StarRating.tsx
> +  return <div className='mt-2 flex justify-center'>{stars}</div>;
Pourquoi ne pas faire un `Array.from` directement dans le return à la place d'une boucle for ?

2023-12-05 13:16 UTC, No3ml3 approved these changes

2023-12-05 13:16 UTC, jaalazard approved these changes
Je suis d'accord

2023-12-05 13:29 UTC, YDrogen approved these changes

2023-12-05 13:29 UTC, merged