feature: favicon
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #82
Opened 2024-02-07 09:36 UTC by Cardamced

Add gorgeous favicon

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [X] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [X] My code follows the style guidelines of this project
- [X] I ran `bun run format`/`bun run lint` before commit
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation where needed
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] I have updated `develop` and merged to my branch before submitting pull request
- [X] My pull request generate no conflicts with `develop` branch
- [X] I requested code review from other team members

## Frontend checklist:

- [X] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [X] My `Javascript` generate no new console errors
- [X] I tested my code cross browsers
- [X] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [X] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-07 09:44 UTC, No3ml3 approved these changes, later dismissed

2024-02-07 09:56 UTC, jaalazard approved these changes, later dismissed

2024-02-08 10:00 UTC, YDrogen requested changes

2024-02-08 10:00 UTC, YDrogen commented on package.json
> +    "react-favicon": "^2.0.3",
Ce package ne sert à rien

2024-02-08 10:00 UTC, YDrogen commented on packages/frontend/web/index.html
> +    />
Il faut remplacer le favicon existant deux lignes au dessus

2024-02-08 10:00 UTC, YDrogen commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
À retirer

2024-02-08 10:00 UTC, YDrogen commented on packages/frontend/web/src/main.tsx
> +export default Main;
Pas utile non plus du coup

2024-02-08 10:24 UTC, Cardamced commented on packages/frontend/web/index.html
> +    />
D'acc. Je ne l'avais pas vu.

2024-02-08 10:24 UTC, Cardamced commented on tsconfig.json
> +  "extends": "expo/tsconfig.base"
Done.

2024-02-08 10:25 UTC, Cardamced commented on package.json
> +    "react-favicon": "^2.0.3",
Bon, la doc que j'avais trouvée me faisait l'installer... mais si ça fonctionne sans, c'était p'têt pas une bonne doc.

2024-02-08 10:26 UTC, Cardamced commented on packages/frontend/web/src/main.tsx
> +export default Main;
C'est enlevé.

2024-02-08 10:36 UTC, jaalazard approved these changes, later dismissed

2024-02-08 15:18 UTC, Justicesvr approved these changes, later dismissed

2024-02-09 10:23 UTC, YDrogen submitted a review, later dismissed

2024-02-09 15:28 UTC, jaalazard approved these changes

2024-02-09 15:28 UTC, Justicesvr approved these changes

2024-02-12 08:53 UTC, YDrogen approved these changes

2024-02-12 08:53 UTC, merged