Feature/carousel and style
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #85
Opened 2024-02-07 10:49 UTC by Justicesvr

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-07 11:04 UTC, No3ml3 submitted a review, later dismissed

2024-02-07 11:07 UTC, Cardamced submitted a review, later dismissed
Ok.

2024-02-08 15:12 UTC, Cardamced approved these changes, later dismissed

2024-02-08 15:58 UTC, jaalazard submitted a review, later dismissed

2024-02-09 10:49 UTC, YDrogen requested changes

2024-02-09 10:49 UTC, YDrogen commented on packages/frontend/web/public/header-profile.png
Pourquoi l'image est aussi grande ? Pourquoi autant de vide autour ?

2024-02-09 10:49 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/Carousel.tsx
> +};
Cette fonction beaucoup trop complexe ne sert à rien :(

2024-02-09 10:49 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/Carousel.tsx
> +      modulo(currentIndex - 1, similarCocktails.length),
```suggestion
      (currentIndex - 1) % similarCocktails.length,
```
Juste ça, ça suffit `number % modulus`

2024-02-09 10:49 UTC, YDrogen commented on packages/frontend/web/src/components/profile-page/CommentsSection.tsx
> +            '"No comments yet"'
C'est normal les quotes dans des quotes ?

2024-02-09 10:49 UTC, YDrogen commented on packages/frontend/web/src/pages/ProfilePage.tsx
> +              {'"There is no cocktails for the moment"'}
même question

2024-02-09 10:49 UTC, YDrogen commented on packages/frontend/web/src/pages/ProfilePage.tsx
> +              {' '}
espace vide normal ?

2024-02-09 10:49 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/Carousel.tsx
> +          className={` ${getClassName(itemIndex)} ${
espace vide

2024-02-14 11:26 UTC, No3ml3 approved these changes, later dismissed

2024-02-14 13:09 UTC, jaalazard submitted a review, later dismissed

2024-02-15 09:42 UTC, YDrogen requested changes

2024-02-15 09:42 UTC, YDrogen commented on packages/backend/api/uploads/42eda93b-68a7-44b1-9c83-688cf3e71acb_cocktail-placeholder.png.png
1) Le contenu de `uploads` ne doit pas être commit (à ajouter au gitignore)
2) Pourquoi `.png.png` ? Y'a un soucis quelque part je pense

2024-02-15 09:42 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/StarRating.tsx
> +export default function StarRating({ rating }: RatingProps) {
C'est une bonne pratique d'appeler le typage des props comme le nom du component avec Props en suffixe
`StarRatingProps`

2024-02-15 09:42 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/SimilarCocktail.tsx
> +import Carrousel from './Carousel';
Faut d'orthographe

2024-02-15 09:42 UTC, YDrogen commented on packages/backend/api/src/comment.ts
> +}
Sert à rien ?

2024-02-15 09:42 UTC, YDrogen commented on packages/backend/api/src/comment.ts
> +      comment.cocktail_id = ${id};
pourquoi
autant
de
sauts
de
lignes
?

2024-02-15 14:46 UTC, jaalazard approved these changes, later dismissed

2024-02-15 14:49 UTC, Cardamced approved these changes, later dismissed

2024-02-15 16:09 UTC, YDrogen requested changes
Il ne faut pas oublier d'ajouter le dossier uploads dans le gitignore

2024-02-15 16:09 UTC, YDrogen commented on packages/frontend/web/src/components/cocktail-detail/StarRating.tsx
> +  readonly rating: number | null | undefined;
Pourquoi `null` ?

2024-02-16 08:30 UTC, No3ml3 submitted a review, later dismissed

2024-02-16 08:48 UTC, Justicesvr commented on packages/frontend/web/public/header-profile.png
ba je ne sais pas c'est comme ca je l'ai exporté sur figma

2024-02-16 14:11 UTC, jaalazard approved these changes, later dismissed

2024-02-20 14:11 UTC, jaalazard approved these changes
Oui

2024-02-20 14:11 UTC, Cardamced approved these changes

2024-02-20 16:09 UTC, YDrogen approved these changes

2024-02-20 16:09 UTC, merged