feat favorite on virgin and profile page
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-a pull request #93
Opened 2024-02-14 16:18 UTC by No3ml3

## Description

favorite on virgin and public profile

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-14 16:22 UTC, jaalazard submitted a review, later dismissed
Oui

2024-02-15 10:19 UTC, Justicesvr approved these changes, later dismissed

2024-02-15 10:46 UTC, YDrogen requested changes

2024-02-15 10:46 UTC, YDrogen commented on packages/backend/api/src/virgin.ts
> +    const virginCocktails = await query.execute();
https://kysely.dev/docs/recipes/conditional-selects

2024-02-15 14:10 UTC, jaalazard approved these changes

2024-02-15 14:21 UTC, Justicesvr approved these changes

2024-02-15 14:45 UTC, YDrogen approved these changes

2024-02-15 14:45 UTC, merged